/* ═══════════════════════════════════════════════════════════
   MANOS VIVAS · idiomas

   Cada texto de la web tiene una clave. Aquí está esa clave
   en español, inglés y francés.

   Para cambiar un texto: búscalo por su clave y edítalo en los
   tres idiomas. El español también está escrito dentro del HTML,
   así que si este archivo no carga, la web sigue en español.
   ═══════════════════════════════════════════════════════════ */

window.__IDIOMAS__ = {
  "es": {
    "a11y.saltar": "Saltar al contenido",
    "nav.masajes": "Masajes",
    "nav.apertura": "Apertura",
    "nav.packs": "Packs",
    "nav.subs": "Suscripción",
    "nav.historia": "Historia",
    "nav.faq": "Preguntas",
    "nav.cta": "Reservar",
    "nav.ctaLargo": "Reservar mi sesión",
    "hero.kicker": "Santiago · A domicilio · Desde 2018",
    "hero.titulo": "Masajes profesionales para volver a <em>sentirte bien</em> en tu cuerpo",
    "hero.bajada": "Una pausa real para regular el estrés, liberar tensión y reconectar contigo. Sesiones desde $55.000.",
    "hero.cta1": "Reservar ahora",
    "hero.cta2": "Conoce nuestros masajes",
    "hero.m1": "Ejerciendo",
    "hero.m2v": "Hotelería",
    "hero.m2": "de lujo",
    "hero.m3": "de masaje neto",
    "ciencia.kicker": "Cuerpo, mente y tacto",
    "ciencia.titulo": "Tu mente no está separada de tu cuerpo",
    "ciencia.p1": "La salud mental también se vive en el cuerpo. Cuando acumulamos estrés, ansiedad o cansancio emocional, el sistema nervioso permanece en alerta y la tensión se instala en músculos, respiración y sueño.",
    "ciencia.p2": "El masaje terapéutico puede ayudar a regular el sistema nervioso autónomo, disminuir la respuesta fisiológica al estrés y favorecer señales corporales asociadas a calma, descanso y bienestar. No es solo una sensación agradable: es una experiencia de cuidado que acompaña la conexión entre cuerpo y mente.",
    "ciencia.aviso": "El masaje es una herramienta complementaria de bienestar y no reemplaza atención médica, psicológica o psiquiátrica cuando esta sea necesaria.",
    "cat.kicker": "Catálogo",
    "cat.titulo": "Nuestros masajes",
    "cat.bajada": "Todos a domicilio y todos adaptables. Cada sesión comienza escuchando cómo llegas, y se ajusta a lo que tu cuerpo necesita ese día.",
    "s1.nombre": "Masaje Relajante",
    "s1.breve": "Para bajar revoluciones, soltar la tensión del día y darle descanso a tu sistema nervioso.",
    "dur.60": "60 min",
    "dur.90": "90 min",
    "cat.conoce": "Conoce más",
    "cat.reservar": "Reservar",
    "s1.detalle": "Usa movimientos suaves y envolventes para favorecer un estado de calma y descanso corporal. Es una buena alternativa cuando te sientes sobrepasado, duermes mal o necesitas salir del ritmo acelerado. Puede apoyar la activación del sistema parasimpático, asociado a recuperación y relajación.",
    "s2.nombre": "Masaje Descontracturante",
    "s2.breve": "Para liberar nudos y tensión acumulada en espalda, cuello, hombros y piernas.",
    "s2.detalle": "Trabaja zonas de carga muscular con presión adaptada a tu tolerancia y necesidades. Es ideal si pasas muchas horas sentado, frente a pantallas, manejando o cargando tensión en el cuerpo. Puede ayudar a mejorar la sensación de movilidad y a disminuir un patrón sostenido de rigidez.",
    "s3.nombre": "Masaje de Tejido Profundo",
    "s3.breve": "Para tensiones persistentes que requieren un trabajo más focalizado y profundo.",
    "s3.detalle": "Se enfoca en capas musculares profundas y zonas con sobrecarga de larga data, siempre respetando tu umbral de comodidad. Es recomendable para personas activas o con tensión muscular recurrente. Puede ayudar a mejorar la percepción de rigidez, movilidad y recuperación corporal.",
    "s4.nombre": "Masaje Deportivo",
    "s4.breve": "Para preparar, acompañar o recuperar tu cuerpo antes y después de la actividad física.",
    "s4.detalle": "Combina técnicas según el momento de entrenamiento y el estado de tu musculatura. Puede ser útil antes de una actividad para preparar el cuerpo, o después para acompañar la recuperación. Está pensado para quienes entrenan, compiten o mantienen una vida físicamente activa.",
    "s5.nombre": "Masaje Mixto",
    "s5.breve": "Calma para la mente y trabajo focalizado para las zonas que más lo necesitan.",
    "s5.detalle": "Combina una base relajante con trabajo descontracturante en áreas específicas. Es una buena elección si buscas bajar el estrés sin dejar de atender cuello, espalda, hombros u otras zonas cargadas. Una sesión equilibrada cuando el cansancio es físico y emocional a la vez.",
    "s6.nombre": "Drenaje Linfático",
    "s6.breve": "Movimientos suaves para acompañar la sensación de liviandad y desinflamación corporal.",
    "s6.detalle": "Utiliza maniobras lentas y delicadas orientadas a favorecer el retorno de líquidos y la sensación de descanso en el cuerpo. Puede ser una alternativa para piernas cansadas, sensación de hinchazón o acompañamiento de bienestar postoperatorio con autorización médica. No reemplaza indicaciones ni controles de profesionales de salud.",
    "s7.nombre": "Mamá a Bordo",
    "s7.breve": "Un espacio de descanso y cuidado corporal adaptado a cada etapa del embarazo.",
    "s7.detalle": "Masaje suave, seguro y adaptado a la comodidad de la futura mamá. Puede ayudar a aliviar sensación de carga corporal, tensión lumbar, cansancio en piernas y estrés propio del embarazo. La posición, presión y duración se ajustan de forma personalizada; requiere evaluación previa y se realiza solo cuando no existan contraindicaciones médicas.",
    "s8.nombre": "Masaje Personalizado",
    "s8.breve": "Una sesión hecha para lo que tu cuerpo necesita hoy, sin fórmulas rígidas.",
    "s8.detalle": "Comenzamos escuchando cómo llegas: estrés, cansancio, zonas cargadas, actividad física, descanso o sensibilidad corporal. A partir de eso, adaptamos las técnicas y la intensidad para crear una sesión a tu medida. Ideal si no sabes qué masaje elegir o si necesitas una experiencia integral.",
    "cat.pie": "Todos los masajes pueden realizarse en versión de 90 minutos, con un adicional de $18.000 sobre el valor de 60 minutos.",
    "ext.kicker": "Complementos",
    "ext.titulo": "Personaliza tu sesión",
    "ext.bajada": "Agrega un complemento y enfoca tu masaje en lo que tu cuerpo necesita hoy.",
    "e1.nombre": "Reflexología",
    "e1.texto": "Trabajo de presión en puntos específicos de los pies para complementar la relajación y promover una mayor conciencia corporal. Ideal si buscas terminar la sesión con una sensación más profunda de descanso.",
    "e2.nombre": "Cérvico Craneal",
    "e2.texto": "Trabajo focalizado en cuello, nuca, mandíbula y cuero cabelludo. Una buena alternativa cuando el estrés se concentra en la cabeza, los hombros o la zona cervical.",
    "e3.nombre": "Head Massage",
    "e3.texto": "Masaje de cuero cabelludo, rostro y cabeza con técnicas suaves y lentas. Pensado para desconectar de pantallas, tensión mental y cansancio acumulado.",
    "ext.tiempo": "Adicionales de tiempo",
    "ext.mas10": "10 minutos adicionales",
    "ext.mas15": "15 minutos adicionales",
    "ext.notaTiempo": "Pueden aplicarse sobre cualquier masaje, incluida la versión de 90 minutos, siempre que la agenda lo permita.",
    "ext.drenaje": "Drenaje linfático adicional",
    "ext.drenaje30": "30 minutos",
    "ext.notaDrenaje": "Se agrega a la sesión elegida para acompañar la sensación de liviandad. No reemplaza indicaciones ni controles de profesionales de salud.",
    "ap.kicker": "Campaña de apertura · Cupos reales",
    "ap.titulo": "Ritual de Apertura",
    "ap.lema": "Dos sesiones para comenzar a volver a tu cuerpo.",
    "ap.desc": "Una experiencia de dos sesiones pensada para que puedas reconocer lo que cambia cuando haces del masaje un momento de cuidado continuo, no solo una pausa aislada.",
    "ap.i1": "2 sesiones de masaje de 60 minutos",
    "ap.i2": "Válido para todos los masajes del catálogo",
    "ap.i3": "Vigencia de 45 días desde la compra",
    "ap.i4": "Exclusivo para clientes nuevos",
    "ap.ahorro": "Ahorras $20.010",
    "ap.pct": "18,2% de descuento",
    "ap.unidad": "Te queda en $44.995 cada sesión",
    "ap.cupos": "cupos disponibles de 10",
    "ap.cta": "Quiero mi Ritual de Apertura",
    "ap.legal": "Exclusivo para nuevos clientes. 10 cupos disponibles. Dos sesiones de 60 min válidas por 45 días. No acumulable con otras promociones.",
    "ap.verCond": "Ver todas las condiciones",
    "ap.c1": "Máximo una compra por persona. No transferible.",
    "ap.c2": "Las dos sesiones deben reservarse y utilizarse dentro de los 45 días.",
    "ap.c3": "No acumulable con packs, suscripciones ni otros descuentos.",
    "ap.c4": "Sujeto a evaluación previa cuando corresponda.",
    "ap.c5": "La versión de 90 minutos no está incluida: se agrega pagando $18.000 por sesión.",
    "ap.c6": "Los adicionales de tiempo y el drenaje linfático adicional se cobran por separado.",
    "pk.kicker": "Packs prepagados",
    "pk.titulo": "Compra ahora, reserva a tu ritmo",
    "pk.bajada": "Adquiere varias sesiones por adelantado y agéndalas cuando quieras durante seis meses.",
    "pk1.nombre": "Pack Chico",
    "pk.sesiones4": "4 sesiones",
    "pk.cada": "$48.750 por sesión",
    "pk1.ahorro": "ahorras 11,4%",
    "pk.cta": "Comprar pack",
    "pk.equilibrio": "El más equilibrado",
    "pk2.nombre": "Pack Mediano",
    "pk.sesiones6": "6 sesiones",
    "pk.cada2": "$49.167 por sesión",
    "pk2.ahorro": "ahorras 10,6%",
    "pk3.nombre": "Pack Grande",
    "pk.sesiones8": "8 sesiones",
    "pk.cada3": "$49.375 por sesión",
    "pk3.ahorro": "ahorras 10,2%",
    "pk.r1": "Vigencia de seis meses desde la fecha de compra.",
    "pk.r2": "Las sesiones se reservan según disponibilidad de agenda.",
    "pk.r3": "La versión de 90 minutos y los adicionales se cobran por separado al reservar cada sesión.",
    "pk.r4": "No acumulable con otras promociones ni descuentos.",
    "su.kicker": "Suscripciones mensuales",
    "su.titulo": "Suscríbete a tu bienestar",
    "su.bajada": "Convierte el cuidado de tu cuerpo en un hábito y accede a mejores precios por sesión.",
    "su1.nombre": "Plan Esencial",
    "su1.sub": "1 sesión al mes",
    "su.mes": "/mes",
    "su1.unidad": "$55.000 por sesión",
    "su.sinPerm": "Sin permanencia",
    "su.cta": "Suscribirme",
    "su2.nombre": "Plan Bienestar",
    "su2.sub": "2 sesiones al mes",
    "su2.unidad": "$52.500 por sesión",
    "su.masElegido": "El más elegido",
    "su3.nombre": "Plan Vital",
    "su3.sub": "4 sesiones al mes",
    "su3.unidad": "$51.250 por sesión",
    "su4.nombre": "Plan Premium",
    "su4.sub": "8 sesiones al mes",
    "su4.unidad": "$47.500 por sesión",
    "su.perm3": "Permanencia mínima de 3 meses",
    "su.r1": "Las sesiones son válidas dentro del mes calendario y no se acumulan para el mes siguiente.",
    "su.r2": "Las suscripciones son personales e intransferibles.",
    "su.r3": "Los planes Esencial, Bienestar y Vital se cancelan cuando quieras, según las condiciones informadas al contratar.",
    "su.r4": "El Plan Premium tiene permanencia mínima de tres meses.",
    "su.r5": "La versión de 90 minutos y los adicionales se cobran por separado al reservar cada sesión.",
    "be.kicker": "Bienestar integral",
    "be.titulo": "Más que relajación: bienestar que se siente en todo el cuerpo",
    "b1.titulo": "Regulación del estrés",
    "b1.texto": "Puede favorecer la activación del sistema parasimpático, asociado al descanso, la recuperación y la sensación de seguridad corporal.",
    "b2.titulo": "Menos tensión acumulada",
    "b2.texto": "El trabajo manual puede ayudar a disminuir rigidez y sobrecarga relacionadas con posturas, entrenamiento, pantallas o estrés sostenido.",
    "b3.titulo": "Mejor descanso",
    "b3.texto": "Una sesión puede ayudar a desacelerar el cuerpo y preparar mejores condiciones para dormir y recuperarse.",
    "b4.titulo": "Conexión cuerpo-mente",
    "b4.texto": "Percibir la respiración, los músculos y las necesidades del cuerpo ayuda a reconocer antes las señales de sobrecarga.",
    "b5.titulo": "Espacio seguro y personalizado",
    "b5.texto": "Cada sesión prioriza escucha, consentimiento, comodidad y adaptación a las necesidades de cada persona.",
    "be.cierre": "No se trata de escapar de tu rutina por una hora. Se trata de darle a tu cuerpo condiciones reales para salir del modo alerta y entrar en modo recuperación.",
    "cf.kicker": "Sin misterio",
    "cf.titulo": "Así de simple",
    "cf1.titulo": "Elige cómo cuidarte",
    "cf1.texto": "Reserva una sesión suelta, compra un pack o suscríbete.",
    "cf2.titulo": "Agenda tu momento",
    "cf2.texto": "Elige servicio, duración, fecha y hora según disponibilidad real.",
    "cf3.titulo": "Personaliza tu experiencia",
    "cf3.texto": "Agrega complementos si los necesitas o convierte la sesión en un regalo.",
    "cf4.titulo": "Vuelve a tu cuerpo",
    "cf4.texto": "Disfruta una sesión adaptada a ti, con cuidado, escucha y respeto.",
    "hi.kicker": "La historia",
    "hi.titulo": "De dónde viene esto",
    "hi.p1": "Cuando uno era chico y se pegaba un golpe, la mamá lo sobaba. El <em>nanay</em>. No curaba nada en términos médicos y sin embargo funcionaba, porque el cuerpo entiende el cariño antes que cualquier otra cosa.",
    "hi.p2": "De adultos nos olvidamos de eso. Nos olvidamos del cuerpo, que es el templo donde vivimos. Y si la máquina no anda bien, el motor termina fallando.",
    "hi.p3": "Soy masoterapeuta desde 2018 y he trabajado en el área de bienestar de hotelería de lujo, donde el estándar no se negocia. Ahí aprendí cómo se hace bien. Pero también he sido cliente, y he pagado masajes de los que me fui pensando «esto no era». Como cocinero al que le sirven mal un plato: sabes exactamente qué faltó.",
    "hi.p4": "Manos Vivas nace de una idea simple: el cuerpo necesita espacios reales para detenerse, ser escuchado y recuperar equilibrio. En medio de rutinas intensas, pantallas, exigencias y cansancio acumulado, creamos un servicio de masaje cercano y profesional que pone a la persona al centro.",
    "hi.p5": "Cada sesión está pensada con privacidad, continuidad y atención personalizada. Escuchamos cómo llegas, respetamos tus límites y construimos una experiencia eficiente, transparente y honesta desde la reserva hasta el final de tu masaje. No buscamos ofrecer una fórmula rápida: buscamos acompañarte a crear una relación más consciente y sostenida con tu bienestar.",
    "hi.cita": "No estoy vendiendo un vaso de agua ni un par de zapatillas: estoy vendiendo el bienestar que te da la motivación para seguir.",
    "hi.firma": "Alejandro Bermúdez · Fundador",
    "hi.misionT": "Misión",
    "hi.mision": "Entregar masajes terapéuticos personalizados que ayuden a las personas a regular el estrés, liberar tensión y reconectar con su bienestar, a través de un servicio profesional, humano, transparente y respetuoso.",
    "hi.visionT": "Visión",
    "hi.vision": "Ser un referente de bienestar corporal en Santiago, reconocido por combinar calidad técnica, cercanía humana, privacidad, continuidad en el cuidado y una experiencia de servicio honesta y eficiente.",
    "hi.rol": "Masoterapeuta · Santiago",
    "te.kicker": "Lo que dicen",
    "te.titulo": "Quienes ya pasaron por la camilla",
    "te.vacio": "Estamos comenzando. Aquí van a estar las palabras de las primeras personas que confíen en Manos Vivas: reales, autorizadas y verificables en Google.",
    "te.pregunta": "¿Ya te atendimos?",
    "te.enlace": "Déjanos tu reseña aquí",
    "fa.kicker": "Antes de reservar",
    "fa.titulo": "Preguntas frecuentes",
    "q1.p": "¿El masaje reemplaza terapia psicológica, atención médica o medicamentos?",
    "q1.r": "No. El masaje es una herramienta complementaria de bienestar. Si experimentas ansiedad, depresión, dolor persistente, embarazo de riesgo u otra condición de salud, consulta al profesional de salud correspondiente.",
    "q2.p": "¿Puedo cancelar mi suscripción?",
    "q2.r": "Sí. Los planes Esencial, Bienestar y Vital se pueden cancelar según las condiciones informadas durante la contratación. El Plan Premium tiene una permanencia mínima de tres meses.",
    "q3.p": "¿Las sesiones se acumulan de un mes a otro?",
    "q3.r": "No. Las sesiones de suscripción son válidas solo dentro del mes calendario. Los packs prepagados tienen una vigencia de seis meses desde la compra.",
    "q4.p": "¿Puedo elegir distintos tipos de masaje con mi pack o suscripción?",
    "q4.r": "Sí, las sesiones pueden utilizarse en los masajes disponibles, previa evaluación y según las necesidades de cada persona. Las excepciones o servicios con condiciones especiales se informan antes de pagar.",
    "q5.p": "¿Puedo agregar reflexología, cérvico craneal o head massage?",
    "q5.r": "Sí. Puedes agregar estos complementos al momento de reservar, sujetos a disponibilidad y al valor adicional vigente.",
    "q6.p": "¿Puedo extender mi sesión 10 o 15 minutos?",
    "q6.r": "Sí. Los adicionales de 10 minutos ($10.000) y 15 minutos ($15.000) pueden aplicarse a cualquier masaje, según disponibilidad de agenda.",
    "q7.p": "¿Puedo elegir una sesión de 90 minutos?",
    "q7.r": "Sí. Todos los masajes del catálogo pueden realizarse en versión de 90 minutos con un adicional de $18.000 sobre el precio base de 60 minutos.",
    "q8.p": "¿El drenaje linfático es adecuado para un postoperatorio?",
    "q8.r": "Puede ser un complemento de bienestar solo con autorización y orientación del equipo médico tratante. No reemplaza controles, indicaciones ni tratamiento clínico.",
    "q9.p": "¿El masaje Mamá a Bordo es seguro durante el embarazo?",
    "q9.r": "Se realiza con evaluación previa, adaptando posición y presión. No debe realizarse si existen contraindicaciones o una indicación médica en contra.",
    "q10.p": "¿Puedo regalar una sesión, pack o suscripción?",
    "q10.r": "Sí. Durante la reserva puedes indicar si la compra es para ti o para regalo, ingresar el nombre de la persona destinataria y un mensaje opcional.",
    "q11.p": "¿A qué comunas llegan?",
    "q11.r": "Cubrimos el sector oriente de Santiago sin costo adicional. Para otras comunas, escríbenos y confirmamos disponibilidad y traslado.",
    "re.kicker": "Reserva",
    "re.titulo": "Arma tu sesión",
    "re.bajada": "Elige, personaliza y agenda. El precio y la duración se actualizan a medida que avanzas.",
    "re.p1": "Elige tu masaje y duración",
    "re.servicio": "Masaje",
    "re.elige": "Elige una opción",
    "re.optApertura": "Ritual de Apertura — 2 sesiones — $89.990",
    "re.optPack4": "Pack Chico — 4 sesiones — $195.000",
    "re.optPack6": "Pack Mediano — 6 sesiones — $295.000",
    "re.optPack8": "Pack Grande — 8 sesiones — $395.000",
    "re.optSub1": "Plan Esencial — $55.000/mes",
    "re.optSub2": "Plan Bienestar — $105.000/mes",
    "re.optSub4": "Plan Vital — $205.000/mes",
    "re.optSub8": "Plan Premium — $380.000/mes",
    "re.duracion": "Duración",
    "re.p2": "Personaliza tu sesión",
    "re.p2nota": "Todo esto es opcional. Puedes seguir sin agregar nada.",
    "re.complementos": "Complementos",
    "re.masTiempo": "Más tiempo",
    "ext.mas10b": "+10 minutos",
    "ext.mas15b": "+15 minutos",
    "ext.drenajeB": "Drenaje linfático",
    "re.p3": "¿Para ti o es un regalo?",
    "re.paraMi": "Es para mí",
    "re.paraRegalo": "Es un regalo",
    "re.regaloNombre": "Nombre de quien recibe el regalo",
    "re.regaloMensaje": "Mensaje para esa persona (opcional)",
    "re.regaloNota": "No pedimos información de salud de la persona destinataria en la compra. La evaluación se realiza en privado antes de la sesión.",
    "re.resumen": "Tu sesión",
    "re.rServicio": "Masaje",
    "re.rDuracion": "Duración total",
    "re.rExtras": "Complementos",
    "re.rPara": "Destinatario",
    "re.total": "Total a pagar",
    "re.p4": "Elige día y hora",
    "re.p4nota": "Se abre nuestro calendario con la duración que elegiste. Solo verás los horarios realmente disponibles.",
    "re.abrirCal": "Abrir el calendario",
    "re.p5": "Confirma y paga",
    "re.acepto": "He leído y acepto los términos, la política de privacidad y las condiciones de cancelación.",
    "re.pagar": "Pagar con MercadoPago",
    "re.wsp": "Confirmar por WhatsApp",
    "re.p5nota": "Tu hora queda confirmada cuando recibes la confirmación del calendario. Para packs, suscripciones y Ritual de Apertura, coordinamos la compra contigo por WhatsApp.",
    "pie.lema": "Volver a sentirte en tu cuerpo",
    "pie.contacto": "Contacto",
    "pie.cobertura": "Cobertura y horarios",
    "pie.zona": "Sector oriente de Santiago",
    "pie.zona2": "Otras comunas, a convenir",
    "pie.horario": "Todos los días, 9:00 a 22:00",
    "pie.sitio": "El sitio",
    "le.cancel": "Cancelación y reprogramación",
    "le.cancelT": "Cancela con al menos 12 horas de anticipación y el valor queda como saldo a tu favor, con vigencia de 3 meses. Los cambios de horario se piden con 24 horas. Con menos aviso, la sesión se considera realizada.",
    "le.vigencia": "Vigencias",
    "le.vigenciaT": "Packs prepagados: 6 meses desde la compra. Ritual de Apertura: 45 días. Suscripciones: las sesiones son válidas dentro del mes calendario y no se acumulan.",
    "le.salud": "Aviso de bienestar",
    "le.saludT": "El masaje es una herramienta complementaria de bienestar y no reemplaza atención médica, psicológica o psiquiátrica. Debes informar tus condiciones de salud antes de la sesión. Algunos casos requieren autorización médica.",
    "le.privacidad": "Privacidad",
    "le.privacidadT": "Usamos tus datos solo para gestionar tu reserva y contactarte. La información de salud se trata de forma confidencial y no se comparte con terceros.",
    "pie.ciudad": "Santiago de Chile",
    "a11y.idioma": "Idioma",
    "a11y.texto": "Tamaño del texto",
    "a11y.menos": "Texto más pequeño",
    "a11y.mas": "Texto más grande",
    "a11y.modo": "Cambiar entre día y noche",
    "a11y.sonido": "Encender el sonido ambiental",
    "a11y.bajar": "Bajar",
    "re.grupoSesiones": "Sesiones",
    "re.grupoOtros": "Apertura, packs y suscripciones",
    "a11y.wsp": "Escribir por WhatsApp",
    "doc.titulo": "Manos Vivas — Masajes terapéuticos a domicilio en Santiago",
    "doc.desc": "Masaje terapéutico a domicilio en Santiago. Regula el estrés, libera tensión y reconecta con tu cuerpo. Sesiones desde $55.000.",
    "a11y.menu": "Abrir menú",
    "a11y.menuCerrar": "Cerrar menú",
    "a11y.sonidoOff": "Apagar el sonido ambiental",
    "cat.cerrar": "Cerrar",
    "re.minutos": "minutos",
    "re.porSesion": "Se agenda sesión por sesión",
    "re.regaloSin": "Regalo",
    "ap.agotado": "Cupos agotados por ahora"
  },

  "en": {
    "a11y.saltar": "Skip to content",
    "nav.masajes": "Massages",
    "nav.apertura": "Opening",
    "nav.packs": "Packs",
    "nav.subs": "Membership",
    "nav.historia": "Story",
    "nav.faq": "FAQ",
    "nav.cta": "Book",
    "nav.ctaLargo": "Book my session",
    "hero.kicker": "Santiago · At home · Since 2018",
    "hero.titulo": "Professional massage to <em>feel at home</em> in your body again",
    "hero.bajada": "A real pause to regulate stress, release tension and reconnect with yourself. Sessions from $55.000.",
    "hero.cta1": "Book now",
    "hero.cta2": "See our massages",
    "hero.m1": "In practice",
    "hero.m2v": "Luxury",
    "hero.m2": "hospitality",
    "hero.m3": "of actual massage",
    "ciencia.kicker": "Body, mind and touch",
    "ciencia.titulo": "Your mind is not separate from your body",
    "ciencia.p1": "Mental health is also lived in the body. When stress, anxiety or emotional fatigue build up, the nervous system stays on alert and tension settles into muscles, breathing and sleep.",
    "ciencia.p2": "Therapeutic massage can help regulate the autonomic nervous system, lower the physiological stress response and encourage bodily signals associated with calm, rest and wellbeing. It is not only a pleasant sensation: it is an experience of care that supports the connection between body and mind.",
    "ciencia.aviso": "Massage is a complementary wellbeing tool and does not replace medical, psychological or psychiatric care when that care is needed.",
    "cat.kicker": "Catalogue",
    "cat.titulo": "Our massages",
    "cat.bajada": "All at home and all adaptable. Every session starts by listening to how you arrive, and adjusts to what your body needs that day.",
    "s1.nombre": "Relaxing Massage",
    "s1.breve": "To slow down, let go of the day's tension and give your nervous system a rest.",
    "dur.60": "60 min",
    "dur.90": "90 min",
    "cat.conoce": "Learn more",
    "cat.reservar": "Book",
    "s1.detalle": "Uses soft, enveloping movements to encourage a state of calm and physical rest. A good choice when you feel overwhelmed, sleep poorly or need to step out of a fast pace. It can support activation of the parasympathetic system, associated with recovery and relaxation.",
    "s2.nombre": "Deep Knot Release Massage",
    "s2.breve": "To release knots and tension built up in the back, neck, shoulders and legs.",
    "s2.detalle": "Works on areas of muscular load with pressure adapted to your tolerance and needs. Ideal if you spend long hours sitting, in front of screens, driving or carrying tension in your body. It can help improve the sense of mobility and ease a sustained pattern of stiffness.",
    "s3.nombre": "Deep Tissue Massage",
    "s3.breve": "For persistent tension that calls for more focused, deeper work.",
    "s3.detalle": "Focuses on deep muscle layers and long-standing overloaded areas, always respecting your comfort threshold. Recommended for active people or those with recurring muscular tension. It can help improve the perception of stiffness, mobility and physical recovery.",
    "s4.nombre": "Sports Massage",
    "s4.breve": "To prepare, support or recover your body before and after physical activity.",
    "s4.detalle": "Combines techniques according to your training phase and the state of your muscles. It can be useful before an activity to prepare the body, or afterwards to support recovery. Designed for people who train, compete or keep a physically active life.",
    "s5.nombre": "Mixed Massage",
    "s5.breve": "Calm for the mind and focused work on the areas that need it most.",
    "s5.detalle": "Combines a relaxing base with knot-release work on specific areas. A good choice if you want to lower stress without neglecting neck, back, shoulders or other loaded areas. A balanced session when tiredness is both physical and emotional.",
    "s6.nombre": "Lymphatic Drainage",
    "s6.breve": "Gentle movements to support a feeling of lightness and reduced puffiness.",
    "s6.detalle": "Uses slow, delicate manoeuvres aimed at supporting fluid return and a sense of rest in the body. It can be an option for tired legs, a feeling of swelling, or post-operative wellbeing support with medical authorisation. It does not replace the instructions or check-ups of health professionals.",
    "s7.nombre": "Mum on Board",
    "s7.breve": "A space of rest and body care adapted to each stage of pregnancy.",
    "s7.detalle": "A gentle, safe massage adapted to the comfort of the mother-to-be. It can help ease the sense of bodily load, lower-back tension, tired legs and the stress that comes with pregnancy. Position, pressure and duration are adjusted individually; it requires a prior assessment and is only performed when there are no medical contraindications.",
    "s8.nombre": "Personalised Massage",
    "s8.breve": "A session built around what your body needs today, with no rigid formulas.",
    "s8.detalle": "We start by listening to how you arrive: stress, tiredness, loaded areas, physical activity, rest or bodily sensitivity. From there we adapt techniques and intensity to create a session made for you. Ideal if you are not sure which massage to choose or want a complete experience.",
    "cat.pie": "Every massage is available in a 90-minute version, for an extra $18.000 on top of the 60-minute price.",
    "ext.kicker": "Add-ons",
    "ext.titulo": "Personalise your session",
    "ext.bajada": "Add a complement and focus your massage on what your body needs today.",
    "e1.nombre": "Reflexology",
    "e1.texto": "Pressure work on specific points of the feet to complement relaxation and encourage greater body awareness. Ideal if you want to end the session with a deeper feeling of rest.",
    "e2.nombre": "Cervical & Cranial",
    "e2.texto": "Focused work on the neck, nape, jaw and scalp. A good option when stress concentrates in the head, shoulders or cervical area.",
    "e3.nombre": "Head Massage",
    "e3.texto": "Scalp, face and head massage with soft, slow techniques. Designed to disconnect from screens, mental tension and accumulated tiredness.",
    "ext.tiempo": "Extra time",
    "ext.mas10": "10 extra minutes",
    "ext.mas15": "15 extra minutes",
    "ext.notaTiempo": "Can be applied to any massage, including the 90-minute version, whenever the schedule allows.",
    "ext.drenaje": "Extra lymphatic drainage",
    "ext.drenaje30": "30 minutes",
    "ext.notaDrenaje": "Added to the chosen session to support a feeling of lightness. It does not replace the instructions or check-ups of health professionals.",
    "ap.kicker": "Opening campaign · Real spots",
    "ap.titulo": "Opening Ritual",
    "ap.lema": "Two sessions to start coming back to your body.",
    "ap.desc": "A two-session experience designed so you can notice what changes when massage becomes ongoing care rather than an isolated pause.",
    "ap.i1": "2 massage sessions of 60 minutes",
    "ap.i2": "Valid for every massage in the catalogue",
    "ap.i3": "Valid for 45 days from purchase",
    "ap.i4": "New clients only",
    "ap.ahorro": "You save $20.010",
    "ap.pct": "18.2% off",
    "ap.unidad": "That is $44.995 per session",
    "ap.cupos": "spots left out of 10",
    "ap.cta": "I want my Opening Ritual",
    "ap.legal": "New clients only. 10 spots available. Two 60-minute sessions valid for 45 days. Not combinable with other promotions.",
    "ap.verCond": "See all conditions",
    "ap.c1": "Maximum one purchase per person. Non-transferable.",
    "ap.c2": "Both sessions must be booked and used within the 45 days.",
    "ap.c3": "Not combinable with packs, memberships or other discounts.",
    "ap.c4": "Subject to prior assessment where applicable.",
    "ap.c5": "The 90-minute version is not included: add it for $18.000 per session.",
    "ap.c6": "Extra time and extra lymphatic drainage are charged separately.",
    "pk.kicker": "Prepaid packs",
    "pk.titulo": "Buy now, book at your own pace",
    "pk.bajada": "Get several sessions in advance and schedule them whenever you like over six months.",
    "pk1.nombre": "Small Pack",
    "pk.sesiones4": "4 sessions",
    "pk.cada": "$48.750 per session",
    "pk1.ahorro": "save 11.4%",
    "pk.cta": "Buy pack",
    "pk.equilibrio": "The most balanced",
    "pk2.nombre": "Medium Pack",
    "pk.sesiones6": "6 sessions",
    "pk.cada2": "$49.167 per session",
    "pk2.ahorro": "save 10.6%",
    "pk3.nombre": "Large Pack",
    "pk.sesiones8": "8 sessions",
    "pk.cada3": "$49.375 per session",
    "pk3.ahorro": "save 10.2%",
    "pk.r1": "Valid for six months from the date of purchase.",
    "pk.r2": "Sessions are booked according to schedule availability.",
    "pk.r3": "The 90-minute version and add-ons are charged separately when booking each session.",
    "pk.r4": "Not combinable with other promotions or discounts.",
    "su.kicker": "Monthly memberships",
    "su.titulo": "Subscribe to your wellbeing",
    "su.bajada": "Turn caring for your body into a habit and get better prices per session.",
    "su1.nombre": "Essential Plan",
    "su1.sub": "1 session per month",
    "su.mes": "/month",
    "su1.unidad": "$55.000 per session",
    "su.sinPerm": "No minimum term",
    "su.cta": "Subscribe",
    "su2.nombre": "Wellbeing Plan",
    "su2.sub": "2 sessions per month",
    "su2.unidad": "$52.500 per session",
    "su.masElegido": "Most chosen",
    "su3.nombre": "Vital Plan",
    "su3.sub": "4 sessions per month",
    "su3.unidad": "$51.250 per session",
    "su4.nombre": "Premium Plan",
    "su4.sub": "8 sessions per month",
    "su4.unidad": "$47.500 per session",
    "su.perm3": "Minimum term of 3 months",
    "su.r1": "Sessions are valid within the calendar month and do not roll over to the next one.",
    "su.r2": "Memberships are personal and non-transferable.",
    "su.r3": "The Essential, Wellbeing and Vital plans can be cancelled whenever you wish, under the conditions given when you sign up.",
    "su.r4": "The Premium Plan has a minimum term of three months.",
    "su.r5": "The 90-minute version and add-ons are charged separately when booking each session.",
    "be.kicker": "Whole-person wellbeing",
    "be.titulo": "More than relaxation: wellbeing you feel throughout your body",
    "b1.titulo": "Stress regulation",
    "b1.texto": "It can encourage activation of the parasympathetic system, associated with rest, recovery and a sense of bodily safety.",
    "b2.titulo": "Less accumulated tension",
    "b2.texto": "Manual work can help reduce stiffness and overload linked to posture, training, screens or sustained stress.",
    "b3.titulo": "Better rest",
    "b3.texto": "A session can help slow the body down and set up better conditions for sleeping and recovering.",
    "b4.titulo": "Body-mind connection",
    "b4.texto": "Noticing your breathing, your muscles and your body's needs helps you recognise the signs of overload sooner.",
    "b5.titulo": "A safe, personalised space",
    "b5.texto": "Every session prioritises listening, consent, comfort and adapting to each person's needs.",
    "be.cierre": "This is not about escaping your routine for an hour. It is about giving your body real conditions to leave alert mode and enter recovery mode.",
    "cf.kicker": "No mystery",
    "cf.titulo": "This simple",
    "cf1.titulo": "Choose how to care for yourself",
    "cf1.texto": "Book a single session, buy a pack or subscribe.",
    "cf2.titulo": "Schedule your moment",
    "cf2.texto": "Choose service, duration, date and time based on real availability.",
    "cf3.titulo": "Personalise your experience",
    "cf3.texto": "Add complements if you need them, or turn the session into a gift.",
    "cf4.titulo": "Come back to your body",
    "cf4.texto": "Enjoy a session adapted to you, with care, listening and respect.",
    "hi.kicker": "The story",
    "hi.titulo": "Where this comes from",
    "hi.p1": "When you were little and hurt yourself, your mother would rub the spot. The <em>nanay</em>. It cured nothing in medical terms and yet it worked, because the body understands affection before anything else.",
    "hi.p2": "As adults we forget that. We forget the body, the temple we live in. And if the machine is not running well, the engine eventually fails.",
    "hi.p3": "I have been a massage therapist since 2018 and have worked in the wellness area of luxury hospitality, where the standard is not up for negotiation. That is where I learned how it is done properly. But I have also been a client, and I have paid for massages I left thinking «that was not it». Like a cook served a badly made dish: you know exactly what was missing.",
    "hi.p4": "Manos Vivas was born from a simple idea: the body needs real spaces to stop, be listened to and recover its balance. In the middle of intense routines, screens, demands and accumulated tiredness, we created a close, professional massage service that puts the person at the centre.",
    "hi.p5": "Every session is designed with privacy, continuity and personal attention. We listen to how you arrive, respect your limits and build an efficient, transparent and honest experience from booking to the end of your massage. We are not offering a quick formula: we want to help you build a more conscious, sustained relationship with your wellbeing.",
    "hi.cita": "I am not selling a glass of water or a pair of trainers: I am selling the wellbeing that gives you the motivation to keep going.",
    "hi.firma": "Alejandro Bermúdez · Founder",
    "hi.misionT": "Mission",
    "hi.mision": "To deliver personalised therapeutic massage that helps people regulate stress, release tension and reconnect with their wellbeing, through a professional, human, transparent and respectful service.",
    "hi.visionT": "Vision",
    "hi.vision": "To be a benchmark for physical wellbeing in Santiago, recognised for combining technical quality, human closeness, privacy, continuity of care and an honest, efficient service experience.",
    "hi.rol": "Massage therapist · Santiago",
    "te.kicker": "What they say",
    "te.titulo": "Those who have already been on the table",
    "te.vacio": "We are just starting. This is where the words of the first people who trust Manos Vivas will be: real, authorised and verifiable on Google.",
    "te.pregunta": "Have we already treated you?",
    "te.enlace": "Leave your review here",
    "fa.kicker": "Before booking",
    "fa.titulo": "Frequently asked questions",
    "q1.p": "Does massage replace psychological therapy, medical care or medication?",
    "q1.r": "No. Massage is a complementary wellbeing tool. If you experience anxiety, depression, persistent pain, a high-risk pregnancy or any other health condition, please consult the relevant health professional.",
    "q2.p": "Can I cancel my membership?",
    "q2.r": "Yes. The Essential, Wellbeing and Vital plans can be cancelled under the conditions given when you sign up. The Premium Plan has a minimum term of three months.",
    "q3.p": "Do sessions roll over from one month to the next?",
    "q3.r": "No. Membership sessions are only valid within the calendar month. Prepaid packs are valid for six months from purchase.",
    "q4.p": "Can I choose different types of massage with my pack or membership?",
    "q4.r": "Yes, sessions can be used for the available massages, subject to assessment and each person's needs. Any exceptions or services with special conditions are explained before you pay.",
    "q5.p": "Can I add reflexology, cervical & cranial or head massage?",
    "q5.r": "Yes. You can add these complements when booking, subject to availability and the current additional price.",
    "q6.p": "Can I extend my session by 10 or 15 minutes?",
    "q6.r": "Yes. The 10-minute ($10.000) and 15-minute ($15.000) add-ons can be applied to any massage, subject to schedule availability.",
    "q7.p": "Can I choose a 90-minute session?",
    "q7.r": "Yes. Every massage in the catalogue is available in a 90-minute version for an extra $18.000 on top of the 60-minute base price.",
    "q8.p": "Is lymphatic drainage suitable after surgery?",
    "q8.r": "It can be a wellbeing complement only with the authorisation and guidance of your treating medical team. It does not replace check-ups, instructions or clinical treatment.",
    "q9.p": "Is the Mum on Board massage safe during pregnancy?",
    "q9.r": "It is performed after a prior assessment, adapting position and pressure. It must not be performed if there are contraindications or medical advice against it.",
    "q10.p": "Can I give a session, pack or membership as a gift?",
    "q10.r": "Yes. When booking you can indicate whether the purchase is for you or a gift, enter the recipient's name and add an optional message.",
    "q11.p": "Which districts do you cover?",
    "q11.r": "We cover the eastern sector of Santiago at no extra cost. For other districts, write to us and we will confirm availability and travel.",
    "re.kicker": "Booking",
    "re.titulo": "Build your session",
    "re.bajada": "Choose, personalise and schedule. Price and duration update as you go.",
    "re.p1": "Choose your massage and duration",
    "re.servicio": "Massage",
    "re.elige": "Choose an option",
    "re.optApertura": "Opening Ritual — 2 sessions — $89.990",
    "re.optPack4": "Small Pack — 4 sessions — $195.000",
    "re.optPack6": "Medium Pack — 6 sessions — $295.000",
    "re.optPack8": "Large Pack — 8 sessions — $395.000",
    "re.optSub1": "Essential Plan — $55.000/month",
    "re.optSub2": "Wellbeing Plan — $105.000/month",
    "re.optSub4": "Vital Plan — $205.000/month",
    "re.optSub8": "Premium Plan — $380.000/month",
    "re.duracion": "Duration",
    "re.p2": "Personalise your session",
    "re.p2nota": "All of this is optional. You can continue without adding anything.",
    "re.complementos": "Complements",
    "re.masTiempo": "More time",
    "ext.mas10b": "+10 minutes",
    "ext.mas15b": "+15 minutes",
    "ext.drenajeB": "Lymphatic drainage",
    "re.p3": "For you or is it a gift?",
    "re.paraMi": "It is for me",
    "re.paraRegalo": "It is a gift",
    "re.regaloNombre": "Name of the person receiving the gift",
    "re.regaloMensaje": "Message for that person (optional)",
    "re.regaloNota": "We do not ask for the recipient's health information at purchase. The assessment is done privately before the session.",
    "re.resumen": "Your session",
    "re.rServicio": "Massage",
    "re.rDuracion": "Total duration",
    "re.rExtras": "Complements",
    "re.rPara": "Recipient",
    "re.total": "Total to pay",
    "re.p4": "Choose day and time",
    "re.p4nota": "Our calendar opens with the duration you chose. You will only see times that are genuinely available.",
    "re.abrirCal": "Open the calendar",
    "re.p5": "Confirm and pay",
    "re.acepto": "I have read and accept the terms, the privacy policy and the cancellation conditions.",
    "re.pagar": "Pay with MercadoPago",
    "re.wsp": "Confirm by WhatsApp",
    "re.p5nota": "Your slot is confirmed when you receive the calendar confirmation. For packs, memberships and the Opening Ritual, we arrange the purchase with you over WhatsApp.",
    "pie.lema": "Feel at home in your body again",
    "pie.contacto": "Contact",
    "pie.cobertura": "Coverage and hours",
    "pie.zona": "Eastern sector of Santiago",
    "pie.zona2": "Other districts, by arrangement",
    "pie.horario": "Every day, 9:00 to 22:00",
    "pie.sitio": "The site",
    "le.cancel": "Cancellation and rescheduling",
    "le.cancelT": "Cancel at least 12 hours in advance and the amount stays as credit in your favour, valid for 3 months. Time changes are requested 24 hours ahead. With less notice, the session is considered delivered.",
    "le.vigencia": "Validity",
    "le.vigenciaT": "Prepaid packs: 6 months from purchase. Opening Ritual: 45 days. Memberships: sessions are valid within the calendar month and do not roll over.",
    "le.salud": "Wellbeing notice",
    "le.saludT": "Massage is a complementary wellbeing tool and does not replace medical, psychological or psychiatric care. You must report your health conditions before the session. Some cases require medical authorisation.",
    "le.privacidad": "Privacy",
    "le.privacidadT": "We use your data only to manage your booking and contact you. Health information is treated confidentially and is not shared with third parties.",
    "pie.ciudad": "Santiago, Chile",
    "a11y.idioma": "Language",
    "a11y.texto": "Text size",
    "a11y.menos": "Smaller text",
    "a11y.mas": "Larger text",
    "a11y.modo": "Switch between day and night",
    "a11y.sonido": "Turn on the ambient sound",
    "a11y.bajar": "Scroll down",
    "re.grupoSesiones": "Sessions",
    "re.grupoOtros": "Opening, packs and memberships",
    "a11y.wsp": "Message on WhatsApp",
    "doc.titulo": "Manos Vivas — Therapeutic massage at home in Santiago",
    "doc.desc": "Therapeutic massage at home in Santiago. Regulate stress, release tension and reconnect with your body. Sessions from $55.000.",
    "a11y.menu": "Open menu",
    "a11y.menuCerrar": "Close menu",
    "a11y.sonidoOff": "Turn off the ambient sound",
    "cat.cerrar": "Close",
    "re.minutos": "minutes",
    "re.porSesion": "Scheduled session by session",
    "re.regaloSin": "Gift",
    "ap.agotado": "No spots left for now"
  },

  "fr": {
    "a11y.saltar": "Aller au contenu",
    "nav.masajes": "Massages",
    "nav.apertura": "Ouverture",
    "nav.packs": "Forfaits",
    "nav.subs": "Abonnement",
    "nav.historia": "Histoire",
    "nav.faq": "Questions",
    "nav.cta": "Réserver",
    "nav.ctaLargo": "Réserver ma séance",
    "hero.kicker": "Santiago · À domicile · Depuis 2018",
    "hero.titulo": "Des massages professionnels pour <em>vous sentir bien</em> à nouveau dans votre corps",
    "hero.bajada": "Une vraie pause pour réguler le stress, libérer les tensions et vous reconnecter à vous-même. Séances à partir de $55.000.",
    "hero.cta1": "Réserver maintenant",
    "hero.cta2": "Découvrir nos massages",
    "hero.m1": "En exercice",
    "hero.m2v": "Hôtellerie",
    "hero.m2": "de luxe",
    "hero.m3": "de massage effectif",
    "ciencia.kicker": "Corps, esprit et toucher",
    "ciencia.titulo": "Votre esprit n'est pas séparé de votre corps",
    "ciencia.p1": "La santé mentale se vit aussi dans le corps. Lorsque le stress, l'anxiété ou la fatigue émotionnelle s'accumulent, le système nerveux reste en alerte et la tension s'installe dans les muscles, la respiration et le sommeil.",
    "ciencia.p2": "Le massage thérapeutique peut aider à réguler le système nerveux autonome, à réduire la réponse physiologique au stress et à favoriser des signaux corporels associés au calme, au repos et au bien-être. Ce n'est pas seulement une sensation agréable : c'est une expérience de soin qui accompagne le lien entre le corps et l'esprit.",
    "ciencia.aviso": "Le massage est un outil complémentaire de bien-être et ne remplace pas un suivi médical, psychologique ou psychiatrique lorsque celui-ci est nécessaire.",
    "cat.kicker": "Catalogue",
    "cat.titulo": "Nos massages",
    "cat.bajada": "Tous à domicile et tous adaptables. Chaque séance commence par écouter comment vous arrivez, puis s'ajuste à ce dont votre corps a besoin ce jour-là.",
    "s1.nombre": "Massage relaxant",
    "s1.breve": "Pour ralentir, relâcher la tension de la journée et offrir du repos à votre système nerveux.",
    "dur.60": "60 min",
    "dur.90": "90 min",
    "cat.conoce": "En savoir plus",
    "cat.reservar": "Réserver",
    "s1.detalle": "Des mouvements doux et enveloppants pour favoriser un état de calme et de repos corporel. Une bonne option lorsque vous vous sentez dépassé, dormez mal ou avez besoin de sortir d'un rythme trop rapide. Il peut soutenir l'activation du système parasympathique, associé à la récupération et à la détente.",
    "s2.nombre": "Massage décontracturant",
    "s2.breve": "Pour libérer les nœuds et la tension accumulée dans le dos, la nuque, les épaules et les jambes.",
    "s2.detalle": "Travaille les zones de charge musculaire avec une pression adaptée à votre tolérance et à vos besoins. Idéal si vous passez de longues heures assis, devant des écrans, au volant, ou si vous portez la tension dans le corps. Il peut aider à améliorer la sensation de mobilité et à réduire une raideur installée.",
    "s3.nombre": "Massage des tissus profonds",
    "s3.breve": "Pour les tensions persistantes qui demandent un travail plus ciblé et plus profond.",
    "s3.detalle": "Se concentre sur les couches musculaires profondes et les zones surchargées de longue date, toujours dans le respect de votre seuil de confort. Recommandé aux personnes actives ou sujettes à des tensions musculaires récurrentes. Il peut aider à améliorer la perception de raideur, la mobilité et la récupération corporelle.",
    "s4.nombre": "Massage sportif",
    "s4.breve": "Pour préparer, accompagner ou récupérer votre corps avant et après l'activité physique.",
    "s4.detalle": "Combine les techniques selon le moment de l'entraînement et l'état de votre musculature. Utile avant une activité pour préparer le corps, ou après pour accompagner la récupération. Pensé pour celles et ceux qui s'entraînent, participent à des compétitions ou mènent une vie physiquement active.",
    "s5.nombre": "Massage mixte",
    "s5.breve": "Du calme pour l'esprit et un travail ciblé sur les zones qui en ont le plus besoin.",
    "s5.detalle": "Associe une base relaxante à un travail décontracturant sur des zones précises. Un bon choix pour faire baisser le stress sans négliger la nuque, le dos, les épaules ou d'autres zones chargées. Une séance équilibrée quand la fatigue est à la fois physique et émotionnelle.",
    "s6.nombre": "Drainage lymphatique",
    "s6.breve": "Des mouvements doux pour accompagner une sensation de légèreté et de dégonflement.",
    "s6.detalle": "Emploie des manœuvres lentes et délicates visant à favoriser le retour des liquides et une sensation de repos dans le corps. Une option possible pour les jambes lourdes, une sensation de gonflement ou un accompagnement de bien-être postopératoire avec autorisation médicale. Il ne remplace ni les indications ni les contrôles des professionnels de santé.",
    "s7.nombre": "Maman à bord",
    "s7.breve": "Un espace de repos et de soin corporel adapté à chaque étape de la grossesse.",
    "s7.detalle": "Un massage doux, sûr et adapté au confort de la future maman. Il peut aider à soulager la sensation de lourdeur, les tensions lombaires, la fatigue des jambes et le stress propre à la grossesse. Position, pression et durée sont ajustées de façon personnalisée ; une évaluation préalable est requise et la séance n'a lieu qu'en l'absence de contre-indications médicales.",
    "s8.nombre": "Massage personnalisé",
    "s8.breve": "Une séance conçue pour ce dont votre corps a besoin aujourd'hui, sans formule rigide.",
    "s8.detalle": "Nous commençons par écouter comment vous arrivez : stress, fatigue, zones chargées, activité physique, repos ou sensibilité corporelle. À partir de là, nous adaptons les techniques et l'intensité pour créer une séance à votre mesure. Idéal si vous ne savez pas quel massage choisir ou si vous cherchez une expérience complète.",
    "cat.pie": "Tous les massages existent en version de 90 minutes, avec un supplément de $18.000 sur le tarif de 60 minutes.",
    "ext.kicker": "Compléments",
    "ext.titulo": "Personnalisez votre séance",
    "ext.bajada": "Ajoutez un complément et orientez votre massage vers ce dont votre corps a besoin aujourd'hui.",
    "e1.nombre": "Réflexologie",
    "e1.texto": "Un travail de pression sur des points précis des pieds pour compléter la détente et favoriser une meilleure conscience corporelle. Idéal pour terminer la séance avec une sensation de repos plus profonde.",
    "e2.nombre": "Cervico-crânien",
    "e2.texto": "Un travail ciblé sur la nuque, le cou, la mâchoire et le cuir chevelu. Une bonne option lorsque le stress se concentre dans la tête, les épaules ou la zone cervicale.",
    "e3.nombre": "Head Massage",
    "e3.texto": "Massage du cuir chevelu, du visage et de la tête avec des techniques douces et lentes. Pensé pour déconnecter des écrans, de la tension mentale et de la fatigue accumulée.",
    "ext.tiempo": "Temps supplémentaire",
    "ext.mas10": "10 minutes de plus",
    "ext.mas15": "15 minutes de plus",
    "ext.notaTiempo": "Applicables à tout massage, y compris la version de 90 minutes, dans la mesure où l'agenda le permet.",
    "ext.drenaje": "Drainage lymphatique supplémentaire",
    "ext.drenaje30": "30 minutes",
    "ext.notaDrenaje": "S'ajoute à la séance choisie pour accompagner la sensation de légèreté. Il ne remplace ni les indications ni les contrôles des professionnels de santé.",
    "ap.kicker": "Campagne d'ouverture · Places réelles",
    "ap.titulo": "Rituel d'ouverture",
    "ap.lema": "Deux séances pour commencer à revenir à votre corps.",
    "ap.desc": "Une expérience en deux séances pensée pour que vous perceviez ce qui change lorsque le massage devient un soin continu plutôt qu'une pause isolée.",
    "ap.i1": "2 séances de massage de 60 minutes",
    "ap.i2": "Valable pour tous les massages du catalogue",
    "ap.i3": "Validité de 45 jours à compter de l'achat",
    "ap.i4": "Réservé aux nouveaux clients",
    "ap.ahorro": "Vous économisez $20.010",
    "ap.pct": "18,2 % de remise",
    "ap.unidad": "Soit $44.995 par séance",
    "ap.cupos": "places disponibles sur 10",
    "ap.cta": "Je veux mon Rituel d'ouverture",
    "ap.legal": "Réservé aux nouveaux clients. 10 places disponibles. Deux séances de 60 min valables 45 jours. Non cumulable avec d'autres promotions.",
    "ap.verCond": "Voir toutes les conditions",
    "ap.c1": "Un achat maximum par personne. Non transférable.",
    "ap.c2": "Les deux séances doivent être réservées et utilisées dans les 45 jours.",
    "ap.c3": "Non cumulable avec les forfaits, les abonnements ou d'autres remises.",
    "ap.c4": "Sous réserve d'une évaluation préalable le cas échéant.",
    "ap.c5": "La version de 90 minutes n'est pas incluse : elle s'ajoute pour $18.000 par séance.",
    "ap.c6": "Les suppléments de temps et le drainage lymphatique supplémentaire sont facturés à part.",
    "pk.kicker": "Forfaits prépayés",
    "pk.titulo": "Achetez maintenant, réservez à votre rythme",
    "pk.bajada": "Achetez plusieurs séances à l'avance et planifiez-les quand vous le souhaitez pendant six mois.",
    "pk1.nombre": "Petit forfait",
    "pk.sesiones4": "4 séances",
    "pk.cada": "$48.750 par séance",
    "pk1.ahorro": "économisez 11,4 %",
    "pk.cta": "Acheter le forfait",
    "pk.equilibrio": "Le plus équilibré",
    "pk2.nombre": "Forfait moyen",
    "pk.sesiones6": "6 séances",
    "pk.cada2": "$49.167 par séance",
    "pk2.ahorro": "économisez 10,6 %",
    "pk3.nombre": "Grand forfait",
    "pk.sesiones8": "8 séances",
    "pk.cada3": "$49.375 par séance",
    "pk3.ahorro": "économisez 10,2 %",
    "pk.r1": "Validité de six mois à compter de la date d'achat.",
    "pk.r2": "Les séances se réservent selon les disponibilités de l'agenda.",
    "pk.r3": "La version de 90 minutes et les compléments sont facturés à part lors de la réservation de chaque séance.",
    "pk.r4": "Non cumulable avec d'autres promotions ou remises.",
    "su.kicker": "Abonnements mensuels",
    "su.titulo": "Abonnez-vous à votre bien-être",
    "su.bajada": "Faites du soin de votre corps une habitude et profitez de meilleurs tarifs par séance.",
    "su1.nombre": "Formule Essentielle",
    "su1.sub": "1 séance par mois",
    "su.mes": "/mois",
    "su1.unidad": "$55.000 par séance",
    "su.sinPerm": "Sans engagement",
    "su.cta": "M'abonner",
    "su2.nombre": "Formule Bien-être",
    "su2.sub": "2 séances par mois",
    "su2.unidad": "$52.500 par séance",
    "su.masElegido": "La plus choisie",
    "su3.nombre": "Formule Vitale",
    "su3.sub": "4 séances par mois",
    "su3.unidad": "$51.250 par séance",
    "su4.nombre": "Formule Premium",
    "su4.sub": "8 séances par mois",
    "su4.unidad": "$47.500 par séance",
    "su.perm3": "Engagement minimum de 3 mois",
    "su.r1": "Les séances sont valables dans le mois calendaire et ne se reportent pas au mois suivant.",
    "su.r2": "Les abonnements sont personnels et non transférables.",
    "su.r3": "Les formules Essentielle, Bien-être et Vitale s'annulent quand vous le souhaitez, selon les conditions communiquées à la souscription.",
    "su.r4": "La formule Premium comporte un engagement minimum de trois mois.",
    "su.r5": "La version de 90 minutes et les compléments sont facturés à part lors de la réservation de chaque séance.",
    "be.kicker": "Bien-être global",
    "be.titulo": "Plus que de la détente : un bien-être qui se ressent dans tout le corps",
    "b1.titulo": "Régulation du stress",
    "b1.texto": "Il peut favoriser l'activation du système parasympathique, associé au repos, à la récupération et à un sentiment de sécurité corporelle.",
    "b2.titulo": "Moins de tension accumulée",
    "b2.texto": "Le travail manuel peut aider à réduire la raideur et la surcharge liées aux postures, à l'entraînement, aux écrans ou à un stress prolongé.",
    "b3.titulo": "Un meilleur repos",
    "b3.texto": "Une séance peut aider à ralentir le corps et à réunir de meilleures conditions pour dormir et récupérer.",
    "b4.titulo": "Lien corps-esprit",
    "b4.texto": "Percevoir sa respiration, ses muscles et les besoins de son corps aide à reconnaître plus tôt les signes de surcharge.",
    "b5.titulo": "Un espace sûr et personnalisé",
    "b5.texto": "Chaque séance privilégie l'écoute, le consentement, le confort et l'adaptation aux besoins de chaque personne.",
    "be.cierre": "Il ne s'agit pas de fuir votre quotidien pendant une heure. Il s'agit d'offrir à votre corps de vraies conditions pour quitter le mode alerte et entrer en mode récupération.",
    "cf.kicker": "Sans mystère",
    "cf.titulo": "Aussi simple que ça",
    "cf1.titulo": "Choisissez comment prendre soin de vous",
    "cf1.texto": "Réservez une séance seule, achetez un forfait ou abonnez-vous.",
    "cf2.titulo": "Planifiez votre moment",
    "cf2.texto": "Choisissez le service, la durée, la date et l'heure selon les disponibilités réelles.",
    "cf3.titulo": "Personnalisez votre expérience",
    "cf3.texto": "Ajoutez des compléments si besoin ou transformez la séance en cadeau.",
    "cf4.titulo": "Revenez à votre corps",
    "cf4.texto": "Profitez d'une séance adaptée à vous, avec soin, écoute et respect.",
    "hi.kicker": "L'histoire",
    "hi.titulo": "D'où vient tout cela",
    "hi.p1": "Quand on était petit et qu'on se faisait mal, notre mère frottait l'endroit. Le <em>nanay</em>. Cela ne guérissait rien au sens médical, et pourtant cela fonctionnait, parce que le corps comprend l'affection avant tout le reste.",
    "hi.p2": "Adultes, nous oublions cela. Nous oublions le corps, ce temple où nous vivons. Et si la machine tourne mal, le moteur finit par lâcher.",
    "hi.p3": "Je suis massothérapeute depuis 2018 et j'ai travaillé dans le secteur bien-être de l'hôtellerie de luxe, où le niveau d'exigence ne se négocie pas. C'est là que j'ai appris comment bien faire. Mais j'ai aussi été client, et j'ai payé des massages dont je suis reparti en me disant « ce n'était pas ça ». Comme un cuisinier mal servi : on sait exactement ce qui a manqué.",
    "hi.p4": "Manos Vivas naît d'une idée simple : le corps a besoin de véritables espaces pour s'arrêter, être écouté et retrouver son équilibre. Au milieu des rythmes intenses, des écrans, des exigences et de la fatigue accumulée, nous avons créé un service de massage proche et professionnel qui place la personne au centre.",
    "hi.p5": "Chaque séance est pensée avec discrétion, continuité et attention personnalisée. Nous écoutons comment vous arrivez, respectons vos limites et construisons une expérience efficace, transparente et honnête, de la réservation jusqu'à la fin de votre massage. Nous ne cherchons pas à proposer une formule rapide : nous voulons vous accompagner vers une relation plus consciente et durable avec votre bien-être.",
    "hi.cita": "Je ne vends pas un verre d'eau ni une paire de baskets : je vends le bien-être qui vous donne la motivation de continuer.",
    "hi.firma": "Alejandro Bermúdez · Fondateur",
    "hi.misionT": "Mission",
    "hi.mision": "Offrir des massages thérapeutiques personnalisés qui aident les personnes à réguler leur stress, libérer leurs tensions et renouer avec leur bien-être, à travers un service professionnel, humain, transparent et respectueux.",
    "hi.visionT": "Vision",
    "hi.vision": "Devenir une référence du bien-être corporel à Santiago, reconnue pour allier qualité technique, proximité humaine, discrétion, continuité du soin et une expérience de service honnête et efficace.",
    "hi.rol": "Massothérapeute · Santiago",
    "te.kicker": "Ce qu'on en dit",
    "te.titulo": "Celles et ceux qui sont déjà passés sur la table",
    "te.vacio": "Nous commençons tout juste. Ici figureront les mots des premières personnes qui feront confiance à Manos Vivas : réels, autorisés et vérifiables sur Google.",
    "te.pregunta": "Nous vous avons déjà reçu ?",
    "te.enlace": "Laissez votre avis ici",
    "fa.kicker": "Avant de réserver",
    "fa.titulo": "Questions fréquentes",
    "q1.p": "Le massage remplace-t-il une thérapie psychologique, un suivi médical ou des médicaments ?",
    "q1.r": "Non. Le massage est un outil complémentaire de bien-être. En cas d'anxiété, de dépression, de douleur persistante, de grossesse à risque ou de toute autre condition de santé, consultez le professionnel de santé concerné.",
    "q2.p": "Puis-je annuler mon abonnement ?",
    "q2.r": "Oui. Les formules Essentielle, Bien-être et Vitale s'annulent selon les conditions communiquées à la souscription. La formule Premium comporte un engagement minimum de trois mois.",
    "q3.p": "Les séances se reportent-elles d'un mois à l'autre ?",
    "q3.r": "Non. Les séances d'abonnement ne sont valables que dans le mois calendaire. Les forfaits prépayés sont valables six mois à compter de l'achat.",
    "q4.p": "Puis-je choisir différents types de massage avec mon forfait ou mon abonnement ?",
    "q4.r": "Oui, les séances peuvent être utilisées pour les massages disponibles, après évaluation et selon les besoins de chaque personne. Les exceptions ou services soumis à conditions particulières sont indiqués avant le paiement.",
    "q5.p": "Puis-je ajouter la réflexologie, le cervico-crânien ou le head massage ?",
    "q5.r": "Oui. Vous pouvez ajouter ces compléments au moment de la réservation, selon les disponibilités et le tarif additionnel en vigueur.",
    "q6.p": "Puis-je prolonger ma séance de 10 ou 15 minutes ?",
    "q6.r": "Oui. Les suppléments de 10 minutes ($10.000) et de 15 minutes ($15.000) sont applicables à tout massage, selon les disponibilités de l'agenda.",
    "q7.p": "Puis-je choisir une séance de 90 minutes ?",
    "q7.r": "Oui. Tous les massages du catalogue existent en version de 90 minutes, avec un supplément de $18.000 sur le tarif de base de 60 minutes.",
    "q8.p": "Le drainage lymphatique convient-il après une opération ?",
    "q8.r": "Il peut être un complément de bien-être uniquement avec l'autorisation et les indications de l'équipe médicale qui vous suit. Il ne remplace ni les contrôles, ni les indications, ni le traitement clinique.",
    "q9.p": "Le massage Maman à bord est-il sûr pendant la grossesse ?",
    "q9.r": "Il se pratique après une évaluation préalable, en adaptant la position et la pression. Il ne doit pas être réalisé en présence de contre-indications ou d'un avis médical contraire.",
    "q10.p": "Puis-je offrir une séance, un forfait ou un abonnement ?",
    "q10.r": "Oui. Lors de la réservation, vous pouvez indiquer si l'achat est pour vous ou s'il s'agit d'un cadeau, saisir le nom de la personne destinataire et ajouter un message facultatif.",
    "q11.p": "Quelles communes desservez-vous ?",
    "q11.r": "Nous couvrons le secteur est de Santiago sans frais supplémentaires. Pour les autres communes, écrivez-nous et nous confirmerons la disponibilité et le déplacement.",
    "re.kicker": "Réservation",
    "re.titulo": "Composez votre séance",
    "re.bajada": "Choisissez, personnalisez et planifiez. Le prix et la durée se mettent à jour au fur et à mesure.",
    "re.p1": "Choisissez votre massage et sa durée",
    "re.servicio": "Massage",
    "re.elige": "Choisissez une option",
    "re.optApertura": "Rituel d'ouverture — 2 séances — $89.990",
    "re.optPack4": "Petit forfait — 4 séances — $195.000",
    "re.optPack6": "Forfait moyen — 6 séances — $295.000",
    "re.optPack8": "Grand forfait — 8 séances — $395.000",
    "re.optSub1": "Formule Essentielle — $55.000/mois",
    "re.optSub2": "Formule Bien-être — $105.000/mois",
    "re.optSub4": "Formule Vitale — $205.000/mois",
    "re.optSub8": "Formule Premium — $380.000/mois",
    "re.duracion": "Durée",
    "re.p2": "Personnalisez votre séance",
    "re.p2nota": "Tout ceci est facultatif. Vous pouvez continuer sans rien ajouter.",
    "re.complementos": "Compléments",
    "re.masTiempo": "Plus de temps",
    "ext.mas10b": "+10 minutes",
    "ext.mas15b": "+15 minutes",
    "ext.drenajeB": "Drainage lymphatique",
    "re.p3": "Pour vous ou est-ce un cadeau ?",
    "re.paraMi": "C'est pour moi",
    "re.paraRegalo": "C'est un cadeau",
    "re.regaloNombre": "Nom de la personne qui reçoit le cadeau",
    "re.regaloMensaje": "Message pour cette personne (facultatif)",
    "re.regaloNota": "Nous ne demandons aucune information de santé sur la personne destinataire lors de l'achat. L'évaluation se fait en privé avant la séance.",
    "re.resumen": "Votre séance",
    "re.rServicio": "Massage",
    "re.rDuracion": "Durée totale",
    "re.rExtras": "Compléments",
    "re.rPara": "Destinataire",
    "re.total": "Total à payer",
    "re.p4": "Choisissez le jour et l'heure",
    "re.p4nota": "Notre agenda s'ouvre avec la durée que vous avez choisie. Vous ne verrez que les créneaux réellement disponibles.",
    "re.abrirCal": "Ouvrir l'agenda",
    "re.p5": "Confirmez et payez",
    "re.acepto": "J'ai lu et j'accepte les conditions, la politique de confidentialité et les conditions d'annulation.",
    "re.pagar": "Payer avec MercadoPago",
    "re.wsp": "Confirmer par WhatsApp",
    "re.p5nota": "Votre créneau est confirmé lorsque vous recevez la confirmation de l'agenda. Pour les forfaits, les abonnements et le Rituel d'ouverture, nous organisons l'achat avec vous par WhatsApp.",
    "pie.lema": "Se sentir à nouveau bien dans son corps",
    "pie.contacto": "Contact",
    "pie.cobertura": "Zone et horaires",
    "pie.zona": "Secteur est de Santiago",
    "pie.zona2": "Autres communes, à convenir",
    "pie.horario": "Tous les jours, 9h00 à 22h00",
    "pie.sitio": "Le site",
    "le.cancel": "Annulation et report",
    "le.cancelT": "Annulez au moins 12 heures à l'avance et le montant reste en crédit à votre nom, valable 3 mois. Les changements d'horaire se demandent 24 heures à l'avance. Avec un préavis plus court, la séance est considérée comme réalisée.",
    "le.vigencia": "Validités",
    "le.vigenciaT": "Forfaits prépayés : 6 mois à compter de l'achat. Rituel d'ouverture : 45 jours. Abonnements : les séances sont valables dans le mois calendaire et ne se reportent pas.",
    "le.salud": "Avis de bien-être",
    "le.saludT": "Le massage est un outil complémentaire de bien-être et ne remplace pas un suivi médical, psychologique ou psychiatrique. Vous devez signaler vos conditions de santé avant la séance. Certains cas nécessitent une autorisation médicale.",
    "le.privacidad": "Confidentialité",
    "le.privacidadT": "Nous utilisons vos données uniquement pour gérer votre réservation et vous contacter. Les informations de santé sont traitées de façon confidentielle et ne sont pas transmises à des tiers.",
    "pie.ciudad": "Santiago du Chili",
    "a11y.idioma": "Langue",
    "a11y.texto": "Taille du texte",
    "a11y.menos": "Texte plus petit",
    "a11y.mas": "Texte plus grand",
    "a11y.modo": "Basculer entre jour et nuit",
    "a11y.sonido": "Activer le son d'ambiance",
    "a11y.bajar": "Descendre",
    "re.grupoSesiones": "Séances",
    "re.grupoOtros": "Ouverture, forfaits et abonnements",
    "a11y.wsp": "Écrire sur WhatsApp",
    "doc.titulo": "Manos Vivas — Massage thérapeutique à domicile à Santiago",
    "doc.desc": "Massage thérapeutique à domicile à Santiago. Régulez le stress, libérez les tensions et renouez avec votre corps. Séances à partir de $55.000.",
    "a11y.menu": "Ouvrir le menu",
    "a11y.menuCerrar": "Fermer le menu",
    "a11y.sonidoOff": "Couper le son d'ambiance",
    "cat.cerrar": "Fermer",
    "re.minutos": "minutes",
    "re.porSesion": "Planifié séance par séance",
    "re.regaloSin": "Cadeau",
    "ap.agotado": "Plus de places pour l'instant"
  }
};
