/* ═══════════════════════════════════════════════════════════
   MANOS VIVAS · idiomas

   Cada texto de la web tiene una clave. Aquí está esa clave
   en español, inglés y francés.

   Para cambiar un texto, búscalo por su clave y edítalo en los
   tres idiomas. El español también está escrito dentro del HTML,
   así que si este archivo no carga, la web sigue en español.
   ═══════════════════════════════════════════════════════════ */

window.IDIOMAS = {
  "es": {
    "a11y.saltar": "Saltar al contenido",
    "nav.ritual": "El ritual",
    "nav.masajes": "Masajes",
    "nav.apertura": "Apertura",
    "nav.planes": "Planes",
    "nav.historia": "Historia",
    "nav.cta": "Reservar",
    "nav.faq": "Preguntas",
    "nav.ctaLargo": "Reservar masaje",
    "hero.label": "Santiago · A domicilio · Desde 2018",
    "hero.titulo": "El bienestar no es <em>negociable</em>.",
    "hero.bajada": "Masaje profesional a domicilio, a tu hora y a tu manera.",
    "hero.cta1": "Reservar masaje",
    "hero.cta2": "Vivir el ritual",
    "hero.s1": "Sesenta minutos son sesenta",
    "hero.s2": "Camilla, aceites y música incluidos",
    "hero.s3": "Desde $55.000",
    "ri.label": "El ritual",
    "ri.titulo": "Así se siente recibirnos en tu casa",
    "ri.bajada": "Cinco momentos. Sin apuro, sin protocolo rígido, sin sorpresas en la cuenta.",
    "ri1.t": "Llegamos a tu puerta",
    "ri1.p": "Puntuales, con camilla, sábanas limpias, aceites y música. Tú no preparas nada.",
    "ri2.t": "Armamos tu espacio",
    "ri2.p": "Elegimos juntos el rincón, la luz y la temperatura. En diez minutos tu casa es otra.",
    "ri3.t": "Eliges tu aceite",
    "ri3.p": "Te ofrecemos tres aromas y hueles cada uno. El que te guste manda.",
    "ri4.t": "Sesenta minutos son sesenta",
    "ri4.p": "El reloj parte cuando parte el masaje. Armar y desarmar no te lo cobramos en tiempo.",
    "ri5.t": "Te dejamos descansando",
    "ri5.p": "Recogemos todo en silencio y nos vamos. Tú te quedas donde estás.",
    "an.label": "Empecemos por ahí",
    "an.titulo": "¿Cómo quieres sentirte hoy?",
    "an.calma": "Bajar revoluciones",
    "an.tension": "Soltar tensión",
    "an.recuperar": "Recuperar tu cuerpo",
    "an.etapa": "Cuidarte en esta etapa",
    "an.nota.calma": "Para bajar el ritmo cuando el día viene cargado.",
    "m1.n": "Masaje Relajante",
    "m1.f": "Para bajar revoluciones y darle descanso a tu sistema nervioso.",
    "d.60": "60 min",
    "d.90": "90 min",
    "m.aporta": "Lo que puede aportar",
    "m.elegir": "Elegir este masaje",
    "m2.n": "Masaje Mixto",
    "m2.f": "Calma para la mente y trabajo puntual donde más pesa.",
    "m3.n": "Masaje Personalizado",
    "m3.f": "Una sesión armada para lo que tu cuerpo pide hoy.",
    "m4.n": "Masaje Descontracturante",
    "m4.f": "Para nudos y carga en espalda, cuello, hombros y piernas.",
    "m5.n": "Tejido Profundo",
    "m5.f": "Para tensiones antiguas que piden un trabajo más hondo.",
    "m6.n": "Masaje Deportivo",
    "m6.f": "Antes o después de entrenar, según lo que necesite tu músculo.",
    "m7.n": "Drenaje Linfático",
    "m7.f": "Movimientos suaves para acompañar la sensación de liviandad.",
    "m8.n": "Mamá a Bordo",
    "m8.f": "Descanso y cuidado adaptados a cada etapa del embarazo.",
    "m.nota": "La versión de 90 minutos vale $18.000 más que la de 60.",
    "ex.label": "Complementos",
    "ex.titulo": "Personaliza tu sesión",
    "ex.bajada": "Se suman al masaje que elijas. El precio y el tiempo, siempre a la vista.",
    "ex1.n": "Reflexología",
    "ex1.d": "Presión en puntos de los pies para cerrar la sesión más hondo.",
    "d.15": "15 min",
    "ex2.n": "Cérvico Craneal",
    "ex2.d": "Cuello, nuca, mandíbula y cuero cabelludo.",
    "ex3.n": "Head Massage",
    "ex3.d": "Cabeza y rostro, lento, para desconectar de las pantallas.",
    "ex4.n": "Tiempo extra",
    "ex4.d": "Diez minutos más de masaje sobre lo que ya elegiste.",
    "d.10": "10 min",
    "ex5.n": "Tiempo extra",
    "ex5.d": "Quince minutos más, cuando el cuerpo pide un poco más.",
    "ex6.n": "Drenaje linfático adicional",
    "ex6.d": "Media hora de drenaje sobre tu sesión.",
    "d.30": "30 min",
    "ap.label": "Ritual de Apertura",
    "ap.titulo": "Dos sesiones para empezar",
    "ap.bajada": "Un masaje suelto se siente bien. Dos, con días de por medio, se notan de otra manera. Por eso el ritual de apertura son dos.",
    "ap.i1": "2 sesiones de 60 minutos",
    "ap.i2": "Cualquier masaje del catálogo",
    "ap.i3": "45 días para usarlas",
    "ap.i4": "10 cupos de apertura",
    "ap.normal": "Valor normal",
    "ap.ahorras": "Ahorras",
    "ap.unidad": "$44.995 cada sesión",
    "ap.cta": "Quiero mi Ritual de Apertura",
    "ap.ver": "Ver condiciones",
    "ap.c1": "Solo para clientes nuevos.",
    "ap.c2": "Una compra por persona, no transferible.",
    "ap.c3": "Vigencia de 45 días desde la compra.",
    "ap.c4": "No se acumula con packs, suscripciones ni otros descuentos.",
    "ap.c5": "La versión de 90 minutos se agrega pagando $18.000 por sesión.",
    "ap.c6": "Los complementos se cobran aparte.",
    "pl.label": "Para seguir",
    "pl.titulo": "Packs y suscripciones",
    "pl.tabPacks": "Packs prepagados",
    "pl.tabSubs": "Suscripciones",
    "pk1.n": "Pack Chico",
    "pk.s4": "4 sesiones",
    "pk1.u": "$48.750 por sesión",
    "pl.cta": "Lo quiero",
    "pl.equilibrado": "El más elegido",
    "pk2.n": "Pack Mediano",
    "pk.s6": "6 sesiones",
    "pk2.u": "$49.167 por sesión",
    "pk3.n": "Pack Grande",
    "pk.s8": "8 sesiones",
    "pk3.u": "$49.375 por sesión",
    "pl.ver": "Ver condiciones",
    "pk.c1": "Vigencia de seis meses desde la compra.",
    "pk.c2": "Las sesiones se agendan según disponibilidad.",
    "pk.c3": "La versión de 90 minutos y los complementos se pagan aparte.",
    "pk.c4": "No se acumula con otras promociones.",
    "su1.n": "Esencial",
    "su1.s": "1 sesión al mes",
    "pl.mes": "/mes",
    "su1.u": "$55.000 por sesión",
    "pl.suscribir": "Suscribirme",
    "su2.n": "Bienestar",
    "su2.s": "2 sesiones al mes",
    "su2.u": "$52.500 por sesión",
    "su3.n": "Vital",
    "su3.s": "4 sesiones al mes",
    "su3.u": "$51.250 por sesión",
    "su4.n": "Premium",
    "su4.s": "8 sesiones al mes",
    "su4.u": "$47.500 por sesión",
    "su4.perm": "Permanencia mínima de 3 meses",
    "su.c1": "Las sesiones valen dentro del mes y no se acumulan para el siguiente.",
    "su.c2": "Las suscripciones son personales e intransferibles.",
    "su.c3": "Esencial, Bienestar y Vital se cancelan cuando quieras.",
    "su.c4": "Premium tiene permanencia mínima de tres meses.",
    "su.c5": "La versión de 90 minutos y los complementos se pagan aparte.",
    "hi.label": "La historia",
    "hi.titulo": "Esto empieza en un <em>nanay</em>",
    "hi.p1": "Cuando uno era chico y se pegaba un golpe, la mamá lo sobaba. No curaba nada en términos médicos y sin embargo funcionaba, porque el cuerpo entiende el cariño antes que cualquier otra cosa. De adultos nos olvidamos de eso.",
    "hi.p2": "Soy masoterapeuta desde 2018 y trabajé en el área de bienestar de hotelería de lujo, donde el estándar no se negocia. Ahí aprendí cómo se hace bien. También he sido cliente, y he pagado masajes de los que me fui pensando «esto no era».",
    "hi.p3": "Manos Vivas es ese estándar llevado a tu casa: privacidad, continuidad y una sesión armada para ti. Cobramos lo que decimos, llegamos cuando decimos y los sesenta minutos son sesenta.",
    "hi.rol": "Masoterapeuta · Fundador",
    "hi.misionT": "Misión",
    "hi.mision": "Llevar masaje profesional y humano a la casa de cada persona, con transparencia, escucha y respeto por sus límites.",
    "hi.visionT": "Visión",
    "hi.vision": "Ser el servicio de masaje a domicilio en el que Santiago confía, por calidad y por honestidad.",
    "fa.label": "Antes de reservar",
    "fa.titulo": "Preguntas frecuentes",
    "q1.p": "¿A qué comunas llegan?",
    "q1.r": "Cubrimos el sector oriente de Santiago sin costo adicional. Para otras comunas, escríbenos y confirmamos disponibilidad.",
    "q2.p": "¿Qué tengo que preparar en mi casa?",
    "q2.r": "Nada. Llevamos camilla, sábanas limpias, aceites y música. Solo necesitamos un espacio de dos por dos metros.",
    "q3.p": "¿Los sesenta minutos incluyen armar y desarmar?",
    "q3.r": "No. El reloj parte cuando parte el masaje. Armar y desarmar corre por nuestra cuenta.",
    "q4.p": "¿El masaje reemplaza atención médica o psicológica?",
    "q4.r": "No. Es una herramienta complementaria de bienestar. Ante dolor persistente, embarazo de riesgo o cualquier condición de salud, consulta a tu profesional tratante.",
    "q5.p": "¿Puedo regalar una sesión?",
    "q5.r": "Sí. Al reservar eliges si agendas tú la hora o si prefieres enviar una tarjeta de regalo para que la persona agende cuando quiera.",
    "q6.p": "¿Cómo se cancela o se cambia la hora?",
    "q6.r": "Avisando con 12 horas, el valor queda como saldo a tu favor por 3 meses. Los cambios de horario se piden con 24 horas.",
    "pie.lema": "Masaje profesional a domicilio, en Santiago.",
    "pie.contacto": "Contacto",
    "pie.cobertura": "Cobertura y horario",
    "pie.zona": "Sector oriente de Santiago",
    "pie.zona2": "Otras comunas, a convenir",
    "pie.horario": "Todos los días, 9:00 a 22:00",
    "pie.legal": "Condiciones",
    "pie.terminos": "Términos",
    "pie.privacidad": "Privacidad",
    "pie.cancelacion": "Cancelación",
    "pie.ciudad": "Santiago de Chile",
    "pie.aviso": "El masaje es una herramienta complementaria de bienestar y no reemplaza atención médica, psicológica ni psiquiátrica.",
    "re.paso1": "Paso 1 de 5",
    "re.t1": "¿Qué quieres reservar?",
    "re.paso2": "Paso 2 de 5",
    "re.t2": "¿Cuánto tiempo?",
    "re.n2": "El tiempo es de masaje puro. Armar y desarmar corre por nuestra cuenta.",
    "re.paso3": "Paso 3 de 5",
    "re.t3": "¿Le sumamos algo?",
    "re.n3": "Todo esto es opcional. Puedes seguir sin agregar nada.",
    "re.mas10": "10 minutos más",
    "re.mas15": "15 minutos más",
    "re.paso4": "Paso 4 de 5",
    "re.t4": "¿Cuándo y para quién?",
    "re.cuando": "Día y horario que prefieres",
    "re.fecha": "Fecha",
    "re.franja": "Franja",
    "re.manana": "Mañana (9:00 a 12:00)",
    "re.tarde": "Tarde (12:00 a 18:00)",
    "re.noche": "Noche (18:00 a 22:00)",
    "re.nFecha": "Es una preferencia, no una hora tomada. Confirmamos por WhatsApp antes de cerrar nada.",
    "re.paraQuien": "¿Para quién es?",
    "re.paraMi": "Para mí",
    "re.paraRegalo": "Es un regalo",
    "re.regaloComo": "¿Cómo lo entregamos?",
    "re.regaloAgendar": "Agendo yo la hora",
    "re.regaloTarjeta": "Envío una tarjeta de regalo",
    "re.regaloNombre": "Nombre de quien lo recibe",
    "re.regaloMensaje": "Mensaje para esa persona (opcional)",
    "re.regaloNota": "Con la tarjeta de regalo, la persona elige el día y la hora cuando quiera, dentro de la vigencia.",
    "re.comuna": "¿En qué comuna?",
    "re.contacto": "Tu WhatsApp o correo",
    "re.paso5": "Paso 5 de 5",
    "re.t5": "Revisa y envía",
    "re.rServicio": "Servicio",
    "re.rDuracion": "Duración total",
    "re.rExtras": "Complementos",
    "re.rCuando": "Preferencia",
    "re.rPara": "Para",
    "re.rTotal": "Total",
    "re.pendienteT": "Solicitud de reserva",
    "re.pendienteP": "Al enviarla, tu hora queda <strong>pendiente de confirmación por WhatsApp</strong>. Te respondemos con la hora exacta y la forma de pago. Todavía no cobramos nada desde la web.",
    "re.acepta": "He leído y acepto los términos, la privacidad y las condiciones de cancelación.",
    "re.enviar": "Enviar solicitud por WhatsApp",
    "re.pagar": "Pagar ahora con Mercado Pago",
    "re.noSalud": "No te pedimos información de salud aquí. Si hay algo que debamos saber, lo conversamos en privado antes de la sesión.",
    "re.atras": "Atrás",
    "re.continuar": "Continuar",
    "a11y.idioma": "Idioma",
    "a11y.animo": "Cómo quieres sentirte",
    "a11y.planes": "Packs y suscripciones",
    "a11y.wsp": "Escribir por WhatsApp",
    "a11y.cerrar": "Cerrar",
    "doc.titulo": "Manos Vivas — Masaje profesional a domicilio en Santiago",
    "doc.desc": "Masaje profesional a domicilio en Santiago. Sesenta minutos son sesenta. Desde $55.000.",
    "a11y.menu": "Abrir menú",
    "a11y.menuCerrar": "Cerrar menú",
    "re.minutos": "minutos",
    "re.varias": "Varias sesiones",
    "re.sinElegir": "Sin elegir",
    "re.regaloSin": "Regalo",
    "re.revisar": "Revisar",
    "op.desde": "Desde",
    "op.apertura": "Ritual de Apertura · 2 sesiones",
    "op.pack4": "Pack Chico · 4 sesiones",
    "op.pack6": "Pack Mediano · 6 sesiones",
    "op.pack8": "Pack Grande · 8 sesiones",
    "op.sub1": "Suscripción Esencial · 1 al mes",
    "op.sub2": "Suscripción Bienestar · 2 al mes",
    "op.sub4": "Suscripción Vital · 4 al mes",
    "op.sub8": "Suscripción Premium · 8 al mes",
    "wsp.saludo": "Hola, quiero reservar en Manos Vivas.",
    "an.nota.tension": "Para los nudos que ya llevan tiempo instalados.",
    "an.nota.recuperar": "Para el cuerpo que entrena, se exige y necesita volver.",
    "an.nota.etapa": "Para cuando tu cuerpo está pasando por algo distinto.",
    "m.relajante.n": "Masaje Relajante",
    "m.relajante.d": "Movimientos suaves y envolventes que ayudan a bajar el ritmo. Puede favorecer un estado de calma y mejor descanso cuando duermes mal o llegas sobrepasado al final del día.",
    "m.mixto.n": "Masaje Mixto",
    "m.mixto.d": "Una base relajante con trabajo puntual en las zonas cargadas. Buena elección cuando el cansancio es físico y emocional a la vez y no quieres elegir entre calmarte o soltar tensión.",
    "m.personalizado.n": "Masaje Personalizado",
    "m.personalizado.d": "Partimos escuchando cómo llegas y armamos la sesión con eso: técnicas, presión y zonas. Ideal si no sabes qué elegir o si tu cuerpo pide algo distinto cada semana.",
    "m.descontracturante.n": "Masaje Descontracturante",
    "m.descontracturante.d": "Trabajo en zonas de carga con presión ajustada a tu tolerancia. Puede ayudar a soltar rigidez de escritorio, pantallas o manejo, y a recuperar sensación de movilidad.",
    "m.profundo.n": "Tejido Profundo",
    "m.profundo.d": "Capas musculares hondas y sobrecargas antiguas, siempre dentro de tu umbral de comodidad. Puede ayudar cuando la tensión vuelve una y otra vez al mismo lugar.",
    "m.deportivo.n": "Masaje Deportivo",
    "m.deportivo.d": "Técnicas según el momento de tu entrenamiento: preparar antes o acompañar la recuperación después. Pensado para quien entrena, compite o se mueve mucho.",
    "m.drenaje.n": "Drenaje Linfático",
    "m.drenaje.d": "Maniobras lentas orientadas a favorecer el retorno de líquidos y la sensación de liviandad. Con autorización médica cuando se trate de un postoperatorio.",
    "m.mama.n": "Mamá a Bordo",
    "m.mama.d": "Masaje suave adaptado a la comodidad de la futura mamá. Puede aliviar carga lumbar, piernas cansadas y tensión del embarazo. Requiere evaluación previa y sin contraindicaciones médicas.",
    "le.terminos.t": "Términos del servicio",
    "le.terminos.p": "Manos Vivas presta masaje terapéutico a domicilio en Santiago. Los precios publicados están en pesos chilenos e incluyen el traslado dentro del sector oriente. Toda reserva hecha desde la web es una solicitud: queda confirmada solo cuando respondemos por WhatsApp con día y hora exactos. El masaje es una herramienta complementaria de bienestar y no reemplaza atención médica, psicológica ni psiquiátrica.",
    "le.privacidad.t": "Privacidad",
    "le.privacidad.p": "Usamos tus datos solo para gestionar tu reserva y contactarte. No pedimos información de salud durante la compra: si hay algo que debamos saber, lo conversamos en privado antes de la sesión y se trata de forma confidencial. No compartimos tus datos con terceros ni los usamos para publicidad.",
    "le.cancelacion.t": "Cancelación y cambios",
    "le.cancelacion.p": "Si cancelas con al menos 12 horas de anticipación, el valor queda como saldo a tu favor con vigencia de 3 meses. Los cambios de horario se piden con 24 horas. Con menos aviso, la sesión se considera realizada. Si somos nosotros quienes no podemos llegar, reagendamos sin costo o devolvemos el total."
  },

  "en": {
    "a11y.saltar": "Skip to content",
    "nav.ritual": "The ritual",
    "nav.masajes": "Massages",
    "nav.apertura": "Opening",
    "nav.planes": "Plans",
    "nav.historia": "Story",
    "nav.cta": "Book",
    "nav.faq": "FAQ",
    "nav.ctaLargo": "Book a massage",
    "hero.label": "Santiago · At home · Since 2018",
    "hero.titulo": "Wellbeing is not <em>negotiable</em>.",
    "hero.bajada": "Professional massage at home, on your time and on your terms.",
    "hero.cta1": "Book a massage",
    "hero.cta2": "See the ritual",
    "hero.s1": "Sixty minutes means sixty",
    "hero.s2": "Table, oils and music included",
    "hero.s3": "From $55.000 CLP",
    "ri.label": "The ritual",
    "ri.titulo": "What it feels like to have us over",
    "ri.bajada": "Five moments. No rush, no rigid protocol, no surprises on the bill.",
    "ri1.t": "We arrive at your door",
    "ri1.p": "On time, with a table, clean sheets, oils and music. You prepare nothing.",
    "ri2.t": "We set up your space",
    "ri2.p": "We pick the corner, the light and the temperature together. Ten minutes and your home is another place.",
    "ri3.t": "You choose your oil",
    "ri3.p": "We offer three scents and you smell each one. Whichever you like wins.",
    "ri4.t": "Sixty minutes means sixty",
    "ri4.p": "The clock starts when the massage starts. Setting up and packing away is on us.",
    "ri5.t": "We leave you resting",
    "ri5.p": "We pack everything in silence and go. You stay right where you are.",
    "an.label": "Let's start there",
    "an.titulo": "How do you want to feel today?",
    "an.calma": "Slow down",
    "an.tension": "Release tension",
    "an.recuperar": "Recover your body",
    "an.etapa": "Care for this stage",
    "an.nota.calma": "For slowing the pace when the day has been heavy.",
    "m1.n": "Relaxing Massage",
    "m1.f": "To slow down and give your nervous system a rest.",
    "d.60": "60 min",
    "d.90": "90 min",
    "m.aporta": "What it can offer",
    "m.elegir": "Choose this massage",
    "m2.n": "Mixed Massage",
    "m2.f": "Calm for the mind and focused work where it weighs most.",
    "m3.n": "Personalised Massage",
    "m3.f": "A session built around what your body is asking for today.",
    "m4.n": "Knot Release Massage",
    "m4.f": "For knots and load in the back, neck, shoulders and legs.",
    "m5.n": "Deep Tissue",
    "m5.f": "For long-standing tension that needs deeper work.",
    "m6.n": "Sports Massage",
    "m6.f": "Before or after training, depending on what your muscles need.",
    "m7.n": "Lymphatic Drainage",
    "m7.f": "Gentle movements to support a feeling of lightness.",
    "m8.n": "Mum on Board",
    "m8.f": "Rest and care adapted to each stage of pregnancy.",
    "m.nota": "The 90-minute version costs $18.000 more than the 60-minute one.",
    "ex.label": "Add-ons",
    "ex.titulo": "Personalise your session",
    "ex.bajada": "They are added to the massage you choose. Price and time always in plain sight.",
    "ex1.n": "Reflexology",
    "ex1.d": "Pressure on points of the feet to close the session deeper.",
    "d.15": "15 min",
    "ex2.n": "Cervical & Cranial",
    "ex2.d": "Neck, nape, jaw and scalp.",
    "ex3.n": "Head Massage",
    "ex3.d": "Head and face, slow, to disconnect from screens.",
    "ex4.n": "Extra time",
    "ex4.d": "Ten more minutes of massage on top of what you chose.",
    "d.10": "10 min",
    "ex5.n": "Extra time",
    "ex5.d": "Fifteen more minutes, when the body asks for a little more.",
    "ex6.n": "Extra lymphatic drainage",
    "ex6.d": "Half an hour of drainage on top of your session.",
    "d.30": "30 min",
    "ap.label": "Opening Ritual",
    "ap.titulo": "Two sessions to begin",
    "ap.bajada": "One massage feels good. Two, with days in between, land differently. That is why the opening ritual is two.",
    "ap.i1": "2 sessions of 60 minutes",
    "ap.i2": "Any massage in the catalogue",
    "ap.i3": "45 days to use them",
    "ap.i4": "10 opening spots",
    "ap.normal": "Normal price",
    "ap.ahorras": "You save",
    "ap.unidad": "$44.995 per session",
    "ap.cta": "I want my Opening Ritual",
    "ap.ver": "See conditions",
    "ap.c1": "New clients only.",
    "ap.c2": "One purchase per person, non-transferable.",
    "ap.c3": "Valid for 45 days from purchase.",
    "ap.c4": "Not combinable with packs, memberships or other discounts.",
    "ap.c5": "The 90-minute version is added for $18.000 per session.",
    "ap.c6": "Add-ons are charged separately.",
    "pl.label": "To keep going",
    "pl.titulo": "Packs and memberships",
    "pl.tabPacks": "Prepaid packs",
    "pl.tabSubs": "Memberships",
    "pk1.n": "Small Pack",
    "pk.s4": "4 sessions",
    "pk1.u": "$48.750 per session",
    "pl.cta": "I want it",
    "pl.equilibrado": "Most chosen",
    "pk2.n": "Medium Pack",
    "pk.s6": "6 sessions",
    "pk2.u": "$49.167 per session",
    "pk3.n": "Large Pack",
    "pk.s8": "8 sessions",
    "pk3.u": "$49.375 per session",
    "pl.ver": "See conditions",
    "pk.c1": "Valid for six months from purchase.",
    "pk.c2": "Sessions are scheduled subject to availability.",
    "pk.c3": "The 90-minute version and add-ons are paid separately.",
    "pk.c4": "Not combinable with other promotions.",
    "su1.n": "Essential",
    "su1.s": "1 session per month",
    "pl.mes": "/month",
    "su1.u": "$55.000 per session",
    "pl.suscribir": "Subscribe",
    "su2.n": "Wellbeing",
    "su2.s": "2 sessions per month",
    "su2.u": "$52.500 per session",
    "su3.n": "Vital",
    "su3.s": "4 sessions per month",
    "su3.u": "$51.250 per session",
    "su4.n": "Premium",
    "su4.s": "8 sessions per month",
    "su4.u": "$47.500 per session",
    "su4.perm": "Minimum term of 3 months",
    "su.c1": "Sessions are valid within the month and do not roll over to the next one.",
    "su.c2": "Memberships are personal and non-transferable.",
    "su.c3": "Essential, Wellbeing and Vital can be cancelled whenever you want.",
    "su.c4": "Premium has a minimum term of three months.",
    "su.c5": "The 90-minute version and add-ons are paid separately.",
    "hi.label": "The story",
    "hi.titulo": "This starts with a <em>nanay</em>",
    "hi.p1": "When you were little and hurt yourself, your mother would rub the spot. It cured nothing in medical terms and yet it worked, because the body understands affection before anything else. As adults we forget that.",
    "hi.p2": "I have been a massage therapist since 2018 and worked in the wellness area of luxury hospitality, where the standard is not up for negotiation. That is where I learned how it is done properly. I have also been a client, and I have paid for massages I left thinking «that was not it».",
    "hi.p3": "Manos Vivas is that standard brought to your home: privacy, continuity and a session built for you. We charge what we say, we arrive when we say, and sixty minutes means sixty.",
    "hi.rol": "Massage therapist · Founder",
    "hi.misionT": "Mission",
    "hi.mision": "To bring professional, human massage into each person's home, with transparency, listening and respect for their limits.",
    "hi.visionT": "Vision",
    "hi.vision": "To be the at-home massage service Santiago trusts, for its quality and its honesty.",
    "fa.label": "Before booking",
    "fa.titulo": "Frequently asked questions",
    "q1.p": "Which districts do you cover?",
    "q1.r": "We cover the eastern sector of Santiago at no extra cost. For other districts, write to us and we will confirm availability.",
    "q2.p": "What do I need to prepare at home?",
    "q2.r": "Nothing. We bring the table, clean sheets, oils and music. We only need a space of two by two metres.",
    "q3.p": "Do the sixty minutes include setting up and packing away?",
    "q3.r": "No. The clock starts when the massage starts. Setting up and packing away is on us.",
    "q4.p": "Does massage replace medical or psychological care?",
    "q4.r": "No. It is a complementary wellbeing tool. For persistent pain, a high-risk pregnancy or any health condition, consult your treating professional.",
    "q5.p": "Can I give a session as a gift?",
    "q5.r": "Yes. When booking you choose whether you schedule the time yourself or send a gift card so the person books whenever they like.",
    "q6.p": "How do I cancel or change the time?",
    "q6.r": "With 12 hours' notice, the amount stays as credit in your favour for 3 months. Time changes are requested 24 hours ahead.",
    "pie.lema": "Professional massage at home, in Santiago.",
    "pie.contacto": "Contact",
    "pie.cobertura": "Coverage and hours",
    "pie.zona": "Eastern sector of Santiago",
    "pie.zona2": "Other districts, by arrangement",
    "pie.horario": "Every day, 9:00 to 22:00",
    "pie.legal": "Conditions",
    "pie.terminos": "Terms",
    "pie.privacidad": "Privacy",
    "pie.cancelacion": "Cancellation",
    "pie.ciudad": "Santiago, Chile",
    "pie.aviso": "Massage is a complementary wellbeing tool and does not replace medical, psychological or psychiatric care.",
    "re.paso1": "Step 1 of 5",
    "re.t1": "What would you like to book?",
    "re.paso2": "Step 2 of 5",
    "re.t2": "How long?",
    "re.n2": "That time is pure massage. Setting up and packing away is on us.",
    "re.paso3": "Step 3 of 5",
    "re.t3": "Shall we add anything?",
    "re.n3": "All of this is optional. You can continue without adding anything.",
    "re.mas10": "10 more minutes",
    "re.mas15": "15 more minutes",
    "re.paso4": "Step 4 of 5",
    "re.t4": "When, and who is it for?",
    "re.cuando": "Day and time you prefer",
    "re.fecha": "Date",
    "re.franja": "Time of day",
    "re.manana": "Morning (9:00 to 12:00)",
    "re.tarde": "Afternoon (12:00 to 18:00)",
    "re.noche": "Evening (18:00 to 22:00)",
    "re.nFecha": "This is a preference, not a booked slot. We confirm by WhatsApp before anything is final.",
    "re.paraQuien": "Who is it for?",
    "re.paraMi": "For me",
    "re.paraRegalo": "It is a gift",
    "re.regaloComo": "How shall we deliver it?",
    "re.regaloAgendar": "I book the time",
    "re.regaloTarjeta": "Send a gift card",
    "re.regaloNombre": "Name of the person receiving it",
    "re.regaloMensaje": "Message for that person (optional)",
    "re.regaloNota": "With the gift card, the person picks the day and time whenever they like, within the validity period.",
    "re.comuna": "Which district?",
    "re.contacto": "Your WhatsApp or email",
    "re.paso5": "Step 5 of 5",
    "re.t5": "Review and send",
    "re.rServicio": "Service",
    "re.rDuracion": "Total duration",
    "re.rExtras": "Add-ons",
    "re.rCuando": "Preference",
    "re.rPara": "For",
    "re.rTotal": "Total",
    "re.pendienteT": "Booking request",
    "re.pendienteP": "When you send it, your slot stays <strong>pending confirmation by WhatsApp</strong>. We reply with the exact time and how to pay. We do not charge anything from the website yet.",
    "re.acepta": "I have read and accept the terms, the privacy policy and the cancellation conditions.",
    "re.enviar": "Send request on WhatsApp",
    "re.pagar": "Pay now with Mercado Pago",
    "re.noSalud": "We do not ask for health information here. If there is something we should know, we discuss it privately before the session.",
    "re.atras": "Back",
    "re.continuar": "Continue",
    "a11y.idioma": "Language",
    "a11y.animo": "How you want to feel",
    "a11y.planes": "Packs and memberships",
    "a11y.wsp": "Message on WhatsApp",
    "a11y.cerrar": "Close",
    "doc.titulo": "Manos Vivas — Professional massage at home in Santiago",
    "doc.desc": "Professional massage at home in Santiago. Sixty minutes means sixty. From $55.000 CLP.",
    "a11y.menu": "Open menu",
    "a11y.menuCerrar": "Close menu",
    "re.minutos": "minutes",
    "re.varias": "Several sessions",
    "re.sinElegir": "Not chosen",
    "re.regaloSin": "Gift",
    "re.revisar": "Review",
    "op.desde": "From",
    "op.apertura": "Opening Ritual · 2 sessions",
    "op.pack4": "Small Pack · 4 sessions",
    "op.pack6": "Medium Pack · 6 sessions",
    "op.pack8": "Large Pack · 8 sessions",
    "op.sub1": "Essential membership · 1 per month",
    "op.sub2": "Wellbeing membership · 2 per month",
    "op.sub4": "Vital membership · 4 per month",
    "op.sub8": "Premium membership · 8 per month",
    "wsp.saludo": "Hello, I would like to book with Manos Vivas.",
    "an.nota.tension": "For the knots that have been settled in for a while.",
    "an.nota.recuperar": "For a body that trains, pushes and needs to come back.",
    "an.nota.etapa": "For when your body is going through something different.",
    "m.relajante.n": "Relaxing Massage",
    "m.relajante.d": "Soft, enveloping movements that help you slow down. It can encourage a state of calm and better rest when you sleep poorly or reach the end of the day overwhelmed.",
    "m.mixto.n": "Mixed Massage",
    "m.mixto.d": "A relaxing base with focused work on loaded areas. A good choice when tiredness is both physical and emotional, and you would rather not choose between calming down and letting go.",
    "m.personalizado.n": "Personalised Massage",
    "m.personalizado.d": "We start by listening to how you arrive and build the session from there: techniques, pressure, areas. Ideal if you are not sure what to choose or your body asks for something different each week.",
    "m.descontracturante.n": "Knot Release Massage",
    "m.descontracturante.d": "Work on loaded areas with pressure matched to your tolerance. It can help release desk, screen or driving stiffness and bring back a sense of mobility.",
    "m.profundo.n": "Deep Tissue",
    "m.profundo.d": "Deep muscle layers and long-standing overload, always within your comfort threshold. It can help when tension keeps returning to the same place.",
    "m.deportivo.n": "Sports Massage",
    "m.deportivo.d": "Techniques matched to your training phase: preparing beforehand or supporting recovery afterwards. Built for people who train, compete or move a lot.",
    "m.drenaje.n": "Lymphatic Drainage",
    "m.drenaje.d": "Slow manoeuvres aimed at supporting fluid return and a feeling of lightness. With medical authorisation when it follows surgery.",
    "m.mama.n": "Mum on Board",
    "m.mama.d": "A gentle massage adapted to the comfort of the mother-to-be. It can ease lower-back load, tired legs and pregnancy tension. Requires a prior assessment and no medical contraindications.",
    "le.terminos.t": "Terms of service",
    "le.terminos.p": "Manos Vivas provides therapeutic massage at home in Santiago. Published prices are in Chilean pesos and include travel within the eastern sector. Any booking made from the website is a request: it is confirmed only when we reply by WhatsApp with the exact day and time. Massage is a complementary wellbeing tool and does not replace medical, psychological or psychiatric care.",
    "le.privacidad.t": "Privacy",
    "le.privacidad.p": "We use your data only to manage your booking and contact you. We do not ask for health information during purchase: if there is something we should know, we discuss it privately before the session and treat it confidentially. We do not share your data with third parties or use it for advertising.",
    "le.cancelacion.t": "Cancellation and changes",
    "le.cancelacion.p": "If you cancel at least 12 hours in advance, the amount stays as credit in your favour, valid for 3 months. Time changes are requested 24 hours ahead. With less notice, the session is considered delivered. If we are the ones who cannot make it, we reschedule at no cost or refund you in full."
  },

  "fr": {
    "a11y.saltar": "Aller au contenu",
    "nav.ritual": "Le rituel",
    "nav.masajes": "Massages",
    "nav.apertura": "Ouverture",
    "nav.planes": "Formules",
    "nav.historia": "Histoire",
    "nav.cta": "Réserver",
    "nav.faq": "Questions",
    "nav.ctaLargo": "Réserver un massage",
    "hero.label": "Santiago · À domicile · Depuis 2018",
    "hero.titulo": "Le bien-être n'est pas <em>négociable</em>.",
    "hero.bajada": "Massage professionnel à domicile, à votre heure et à votre façon.",
    "hero.cta1": "Réserver un massage",
    "hero.cta2": "Vivre le rituel",
    "hero.s1": "Soixante minutes, c'est soixante",
    "hero.s2": "Table, huiles et musique inclus",
    "hero.s3": "À partir de $55.000 CLP",
    "ri.label": "Le rituel",
    "ri.titulo": "Ce que l'on ressent quand on nous reçoit chez soi",
    "ri.bajada": "Cinq moments. Sans hâte, sans protocole rigide, sans surprise sur la note.",
    "ri1.t": "Nous arrivons chez vous",
    "ri1.p": "À l'heure, avec la table, des draps propres, les huiles et la musique. Vous ne préparez rien.",
    "ri2.t": "Nous installons votre espace",
    "ri2.p": "Nous choisissons ensemble le coin, la lumière et la température. En dix minutes, votre maison devient autre.",
    "ri3.t": "Vous choisissez votre huile",
    "ri3.p": "Nous proposons trois parfums et vous sentez chacun. Celui qui vous plaît décide.",
    "ri4.t": "Soixante minutes, c'est soixante",
    "ri4.p": "Le compteur démarre avec le massage. L'installation et le rangement sont pour nous.",
    "ri5.t": "Nous vous laissons au repos",
    "ri5.p": "Nous rangeons tout en silence et nous partons. Vous restez où vous êtes.",
    "an.label": "Commençons par là",
    "an.titulo": "Comment voulez-vous vous sentir aujourd'hui ?",
    "an.calma": "Ralentir",
    "an.tension": "Relâcher les tensions",
    "an.recuperar": "Récupérer votre corps",
    "an.etapa": "Prendre soin de cette étape",
    "an.nota.calma": "Pour ralentir quand la journée a été lourde.",
    "m1.n": "Massage relaxant",
    "m1.f": "Pour ralentir et offrir du repos à votre système nerveux.",
    "d.60": "60 min",
    "d.90": "90 min",
    "m.aporta": "Ce que cela peut apporter",
    "m.elegir": "Choisir ce massage",
    "m2.n": "Massage mixte",
    "m2.f": "Du calme pour l'esprit et un travail ciblé là où ça pèse le plus.",
    "m3.n": "Massage personnalisé",
    "m3.f": "Une séance construite pour ce que votre corps demande aujourd'hui.",
    "m4.n": "Massage décontracturant",
    "m4.f": "Pour les nœuds et la charge dans le dos, la nuque, les épaules et les jambes.",
    "m5.n": "Tissus profonds",
    "m5.f": "Pour les tensions anciennes qui demandent un travail plus profond.",
    "m6.n": "Massage sportif",
    "m6.f": "Avant ou après l'entraînement, selon ce dont vos muscles ont besoin.",
    "m7.n": "Drainage lymphatique",
    "m7.f": "Des mouvements doux pour accompagner la sensation de légèreté.",
    "m8.n": "Maman à bord",
    "m8.f": "Repos et soin adaptés à chaque étape de la grossesse.",
    "m.nota": "La version de 90 minutes coûte $18.000 de plus que celle de 60.",
    "ex.label": "Compléments",
    "ex.titulo": "Personnalisez votre séance",
    "ex.bajada": "Ils s'ajoutent au massage choisi. Le prix et le temps, toujours visibles.",
    "ex1.n": "Réflexologie",
    "ex1.d": "Pression sur des points des pieds pour clore la séance plus profondément.",
    "d.15": "15 min",
    "ex2.n": "Cervico-crânien",
    "ex2.d": "Nuque, cou, mâchoire et cuir chevelu.",
    "ex3.n": "Head Massage",
    "ex3.d": "Tête et visage, lentement, pour déconnecter des écrans.",
    "ex4.n": "Temps supplémentaire",
    "ex4.d": "Dix minutes de massage en plus de ce que vous avez choisi.",
    "d.10": "10 min",
    "ex5.n": "Temps supplémentaire",
    "ex5.d": "Quinze minutes de plus, quand le corps en demande un peu plus.",
    "ex6.n": "Drainage lymphatique supplémentaire",
    "ex6.d": "Une demi-heure de drainage en plus de votre séance.",
    "d.30": "30 min",
    "ap.label": "Rituel d'ouverture",
    "ap.titulo": "Deux séances pour commencer",
    "ap.bajada": "Un massage isolé fait du bien. Deux, espacés de quelques jours, se ressentent autrement. C'est pour cela que le rituel d'ouverture en compte deux.",
    "ap.i1": "2 séances de 60 minutes",
    "ap.i2": "N'importe quel massage du catalogue",
    "ap.i3": "45 jours pour les utiliser",
    "ap.i4": "10 places d'ouverture",
    "ap.normal": "Prix normal",
    "ap.ahorras": "Vous économisez",
    "ap.unidad": "$44.995 par séance",
    "ap.cta": "Je veux mon Rituel d'ouverture",
    "ap.ver": "Voir les conditions",
    "ap.c1": "Réservé aux nouveaux clients.",
    "ap.c2": "Un achat par personne, non transférable.",
    "ap.c3": "Validité de 45 jours à compter de l'achat.",
    "ap.c4": "Non cumulable avec les forfaits, les abonnements ou d'autres remises.",
    "ap.c5": "La version de 90 minutes s'ajoute pour $18.000 par séance.",
    "ap.c6": "Les compléments sont facturés à part.",
    "pl.label": "Pour continuer",
    "pl.titulo": "Forfaits et abonnements",
    "pl.tabPacks": "Forfaits prépayés",
    "pl.tabSubs": "Abonnements",
    "pk1.n": "Petit forfait",
    "pk.s4": "4 séances",
    "pk1.u": "$48.750 par séance",
    "pl.cta": "Je le veux",
    "pl.equilibrado": "Le plus choisi",
    "pk2.n": "Forfait moyen",
    "pk.s6": "6 séances",
    "pk2.u": "$49.167 par séance",
    "pk3.n": "Grand forfait",
    "pk.s8": "8 séances",
    "pk3.u": "$49.375 par séance",
    "pl.ver": "Voir les conditions",
    "pk.c1": "Validité de six mois à compter de l'achat.",
    "pk.c2": "Les séances se planifient selon les disponibilités.",
    "pk.c3": "La version de 90 minutes et les compléments se paient à part.",
    "pk.c4": "Non cumulable avec d'autres promotions.",
    "su1.n": "Essentielle",
    "su1.s": "1 séance par mois",
    "pl.mes": "/mois",
    "su1.u": "$55.000 par séance",
    "pl.suscribir": "M'abonner",
    "su2.n": "Bien-être",
    "su2.s": "2 séances par mois",
    "su2.u": "$52.500 par séance",
    "su3.n": "Vitale",
    "su3.s": "4 séances par mois",
    "su3.u": "$51.250 par séance",
    "su4.n": "Premium",
    "su4.s": "8 séances par mois",
    "su4.u": "$47.500 par séance",
    "su4.perm": "Engagement minimum de 3 mois",
    "su.c1": "Les séances sont valables dans le mois et ne se reportent pas au suivant.",
    "su.c2": "Les abonnements sont personnels et non transférables.",
    "su.c3": "Essentielle, Bien-être et Vitale s'annulent quand vous le souhaitez.",
    "su.c4": "Premium comporte un engagement minimum de trois mois.",
    "su.c5": "La version de 90 minutes et les compléments se paient à part.",
    "hi.label": "L'histoire",
    "hi.titulo": "Tout commence par un <em>nanay</em>",
    "hi.p1": "Quand on était petit et qu'on se faisait mal, notre mère frottait l'endroit. Cela ne guérissait rien au sens médical, et pourtant cela fonctionnait, parce que le corps comprend l'affection avant tout le reste. Adultes, nous l'oublions.",
    "hi.p2": "Je suis massothérapeute depuis 2018 et j'ai travaillé dans le secteur bien-être de l'hôtellerie de luxe, où le niveau d'exigence ne se négocie pas. C'est là que j'ai appris comment bien faire. J'ai aussi été client, et j'ai payé des massages dont je suis reparti en me disant « ce n'était pas ça ».",
    "hi.p3": "Manos Vivas, c'est ce niveau d'exigence porté chez vous : discrétion, continuité et une séance construite pour vous. Nous facturons ce que nous annonçons, nous arrivons quand nous le disons, et soixante minutes, c'est soixante.",
    "hi.rol": "Massothérapeute · Fondateur",
    "hi.misionT": "Mission",
    "hi.mision": "Porter un massage professionnel et humain au domicile de chaque personne, avec transparence, écoute et respect de ses limites.",
    "hi.visionT": "Vision",
    "hi.vision": "Devenir le service de massage à domicile auquel Santiago fait confiance, pour sa qualité et son honnêteté.",
    "fa.label": "Avant de réserver",
    "fa.titulo": "Questions fréquentes",
    "q1.p": "Quelles communes desservez-vous ?",
    "q1.r": "Nous couvrons le secteur est de Santiago sans frais supplémentaires. Pour les autres communes, écrivez-nous et nous confirmerons la disponibilité.",
    "q2.p": "Que dois-je préparer chez moi ?",
    "q2.r": "Rien. Nous apportons la table, des draps propres, les huiles et la musique. Il nous faut seulement un espace de deux mètres sur deux.",
    "q3.p": "Les soixante minutes incluent-elles l'installation et le rangement ?",
    "q3.r": "Non. Le compteur démarre avec le massage. L'installation et le rangement sont à notre charge.",
    "q4.p": "Le massage remplace-t-il un suivi médical ou psychologique ?",
    "q4.r": "Non. C'est un outil complémentaire de bien-être. En cas de douleur persistante, de grossesse à risque ou de toute condition de santé, consultez votre professionnel traitant.",
    "q5.p": "Puis-je offrir une séance ?",
    "q5.r": "Oui. Au moment de réserver, vous choisissez de fixer l'heure vous-même ou d'envoyer une carte cadeau pour que la personne réserve quand elle le souhaite.",
    "q6.p": "Comment annuler ou changer l'heure ?",
    "q6.r": "Avec 12 heures de préavis, le montant reste en crédit à votre nom pendant 3 mois. Les changements d'horaire se demandent 24 heures à l'avance.",
    "pie.lema": "Massage professionnel à domicile, à Santiago.",
    "pie.contacto": "Contact",
    "pie.cobertura": "Zone et horaires",
    "pie.zona": "Secteur est de Santiago",
    "pie.zona2": "Autres communes, à convenir",
    "pie.horario": "Tous les jours, 9h00 à 22h00",
    "pie.legal": "Conditions",
    "pie.terminos": "Conditions",
    "pie.privacidad": "Confidentialité",
    "pie.cancelacion": "Annulation",
    "pie.ciudad": "Santiago du Chili",
    "pie.aviso": "Le massage est un outil complémentaire de bien-être et ne remplace pas un suivi médical, psychologique ou psychiatrique.",
    "re.paso1": "Étape 1 sur 5",
    "re.t1": "Que souhaitez-vous réserver ?",
    "re.paso2": "Étape 2 sur 5",
    "re.t2": "Combien de temps ?",
    "re.n2": "Ce temps est du massage pur. L'installation et le rangement sont à notre charge.",
    "re.paso3": "Étape 3 sur 5",
    "re.t3": "On ajoute quelque chose ?",
    "re.n3": "Tout ceci est facultatif. Vous pouvez continuer sans rien ajouter.",
    "re.mas10": "10 minutes de plus",
    "re.mas15": "15 minutes de plus",
    "re.paso4": "Étape 4 sur 5",
    "re.t4": "Quand, et pour qui ?",
    "re.cuando": "Jour et horaire souhaités",
    "re.fecha": "Date",
    "re.franja": "Moment",
    "re.manana": "Matin (9h00 à 12h00)",
    "re.tarde": "Après-midi (12h00 à 18h00)",
    "re.noche": "Soir (18h00 à 22h00)",
    "re.nFecha": "C'est une préférence, pas un créneau réservé. Nous confirmons par WhatsApp avant de rien fixer.",
    "re.paraQuien": "C'est pour qui ?",
    "re.paraMi": "Pour moi",
    "re.paraRegalo": "C'est un cadeau",
    "re.regaloComo": "Comment le remettons-nous ?",
    "re.regaloAgendar": "Je fixe l'heure",
    "re.regaloTarjeta": "J'envoie une carte cadeau",
    "re.regaloNombre": "Nom de la personne qui le reçoit",
    "re.regaloMensaje": "Message pour cette personne (facultatif)",
    "re.regaloNota": "Avec la carte cadeau, la personne choisit le jour et l'heure quand elle le souhaite, dans la période de validité.",
    "re.comuna": "Dans quelle commune ?",
    "re.contacto": "Votre WhatsApp ou e-mail",
    "re.paso5": "Étape 5 sur 5",
    "re.t5": "Vérifiez et envoyez",
    "re.rServicio": "Service",
    "re.rDuracion": "Durée totale",
    "re.rExtras": "Compléments",
    "re.rCuando": "Préférence",
    "re.rPara": "Pour",
    "re.rTotal": "Total",
    "re.pendienteT": "Demande de réservation",
    "re.pendienteP": "En l'envoyant, votre créneau reste <strong>en attente de confirmation par WhatsApp</strong>. Nous répondons avec l'heure exacte et le mode de paiement. Nous ne prélevons encore rien depuis le site.",
    "re.acepta": "J'ai lu et j'accepte les conditions, la confidentialité et les conditions d'annulation.",
    "re.enviar": "Envoyer la demande sur WhatsApp",
    "re.pagar": "Payer maintenant avec Mercado Pago",
    "re.noSalud": "Nous ne demandons aucune information de santé ici. S'il y a quelque chose à savoir, nous en parlons en privé avant la séance.",
    "re.atras": "Retour",
    "re.continuar": "Continuer",
    "a11y.idioma": "Langue",
    "a11y.animo": "Comment vous voulez vous sentir",
    "a11y.planes": "Forfaits et abonnements",
    "a11y.wsp": "Écrire sur WhatsApp",
    "a11y.cerrar": "Fermer",
    "doc.titulo": "Manos Vivas — Massage professionnel à domicile à Santiago",
    "doc.desc": "Massage professionnel à domicile à Santiago. Soixante minutes, c'est soixante. À partir de $55.000 CLP.",
    "a11y.menu": "Ouvrir le menu",
    "a11y.menuCerrar": "Fermer le menu",
    "re.minutos": "minutes",
    "re.varias": "Plusieurs séances",
    "re.sinElegir": "Non choisi",
    "re.regaloSin": "Cadeau",
    "re.revisar": "Vérifier",
    "op.desde": "À partir de",
    "op.apertura": "Rituel d'ouverture · 2 séances",
    "op.pack4": "Petit forfait · 4 séances",
    "op.pack6": "Forfait moyen · 6 séances",
    "op.pack8": "Grand forfait · 8 séances",
    "op.sub1": "Abonnement Essentielle · 1 par mois",
    "op.sub2": "Abonnement Bien-être · 2 par mois",
    "op.sub4": "Abonnement Vitale · 4 par mois",
    "op.sub8": "Abonnement Premium · 8 par mois",
    "wsp.saludo": "Bonjour, je souhaite réserver chez Manos Vivas.",
    "an.nota.tension": "Pour les nœuds installés depuis un moment.",
    "an.nota.recuperar": "Pour un corps qui s'entraîne, s'exige et doit revenir.",
    "an.nota.etapa": "Pour les moments où votre corps traverse quelque chose de différent.",
    "m.relajante.n": "Massage relaxant",
    "m.relajante.d": "Des mouvements doux et enveloppants qui aident à ralentir. Cela peut favoriser un état de calme et un meilleur repos quand vous dormez mal ou finissez la journée dépassé.",
    "m.mixto.n": "Massage mixte",
    "m.mixto.d": "Une base relaxante avec un travail ciblé sur les zones chargées. Un bon choix quand la fatigue est à la fois physique et émotionnelle et que vous ne voulez pas choisir entre les deux.",
    "m.personalizado.n": "Massage personnalisé",
    "m.personalizado.d": "Nous commençons par écouter comment vous arrivez et bâtissons la séance à partir de là : techniques, pression, zones. Idéal si vous hésitez ou si votre corps demande autre chose chaque semaine.",
    "m.descontracturante.n": "Massage décontracturant",
    "m.descontracturante.d": "Un travail sur les zones chargées avec une pression ajustée à votre tolérance. Cela peut aider à relâcher la raideur du bureau, des écrans ou de la conduite et à retrouver de la mobilité.",
    "m.profundo.n": "Tissus profonds",
    "m.profundo.d": "Couches musculaires profondes et surcharges anciennes, toujours dans votre seuil de confort. Cela peut aider quand la tension revient sans cesse au même endroit.",
    "m.deportivo.n": "Massage sportif",
    "m.deportivo.d": "Des techniques adaptées au moment de votre entraînement : préparer avant ou accompagner la récupération après. Pensé pour celles et ceux qui s'entraînent, concourent ou bougent beaucoup.",
    "m.drenaje.n": "Drainage lymphatique",
    "m.drenaje.d": "Des manœuvres lentes visant à favoriser le retour des liquides et une sensation de légèreté. Avec autorisation médicale lorsqu'il s'agit d'un postopératoire.",
    "m.mama.n": "Maman à bord",
    "m.mama.d": "Un massage doux adapté au confort de la future maman. Il peut soulager la charge lombaire, les jambes fatiguées et la tension de la grossesse. Évaluation préalable requise et sans contre-indication médicale.",
    "le.terminos.t": "Conditions du service",
    "le.terminos.p": "Manos Vivas propose un massage thérapeutique à domicile à Santiago. Les prix affichés sont en pesos chiliens et incluent le déplacement dans le secteur est. Toute réservation faite depuis le site est une demande : elle n'est confirmée que lorsque nous répondons par WhatsApp avec le jour et l'heure exacts. Le massage est un outil complémentaire de bien-être et ne remplace pas un suivi médical, psychologique ou psychiatrique.",
    "le.privacidad.t": "Confidentialité",
    "le.privacidad.p": "Nous utilisons vos données uniquement pour gérer votre réservation et vous contacter. Nous ne demandons pas d'informations de santé lors de l'achat : s'il y a quelque chose à savoir, nous en parlons en privé avant la séance et cela reste confidentiel. Nous ne partageons pas vos données et ne les utilisons pas à des fins publicitaires.",
    "le.cancelacion.t": "Annulation et changements",
    "le.cancelacion.p": "Si vous annulez au moins 12 heures à l'avance, le montant reste en crédit à votre nom, valable 3 mois. Les changements d'horaire se demandent 24 heures à l'avance. Avec un préavis plus court, la séance est considérée comme réalisée. Si c'est nous qui ne pouvons pas venir, nous reprogrammons sans frais ou remboursons intégralement."
  }
};
